### ISSUE TITLE
Monitor memory usage of VT components

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1009]
**What Needs to be Done?**

We've been trying to solve some memory growth in EMPIRE. However, it's difficult to tell where memory increase might occur. Thus, the idea is to add a virtual component method for reporting memory usage across the all the VT components. To do this, we should add serializers (that count the size at the least---doesn't have to serialize properly) to the VT components and then invoke `checkpoint::getSize` on the component.

**Comment by PhilMiller** [comment]
Following on this, we'll want to expand on our test suite to 
- [ ] Run the serialization sanitizer over all of the components
- [ ] Add tests that exercise essentially everything over many iterations, to hunt for growth
