### ISSUE TITLE
Fix NodeStats LB stat file output

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1014]
**What Needs to be Done?**

Currently, after trimming NodeStats the LB mapping/stats file is no longer being output correctly.

**Comment by lifflander** [comment]
@jstrzebonski Please work on this next!

With https://github.com/DARMA-tasking/vt/pull/995 merged, we are trimming the data that is stored in `NodeStats` every phase based on how much past data is required but the models. However, the stat file output currently works by outputting at the very end. Now that it is being trimming, the LB stat file output will not output all the phases because they have been deleted from the `NodeStats` history. Thus, when stat file output is enabled, we need to incrementally write the stats for each phase to the stat file on each node.

See this part of the [manual](https://darma-tasking.github.io/docs/html/node-stats.html#export-lb-stats-file) for an explanation of how stat file are exported.

**Comment by jstrzebonski** [comment]
@lifflander I think that the easiest way to do it is to call `outputStatsFile()` with a given phase to dump the stats for (something like this: `void NodeStats::outputStatsFileForPhase(PhaseType phase)`). Now the questions are:
1. When to do it? I'm not yet that familiar with the code, but my blind guess would be to do it just before `theNodeStats()->startIterCleanup(phase, model_->getNumPastPhasesNeeded());`. Is that OK?
2. (_this might be very stupid question, but I want to be sure_)
If 1. is OK then would doing so dump stats for all phases, or could there be some (the last one) that still needs to be save to file before the program ends?
3. (_next not very smart question..._)
I'm not really sure of the size of calculations that vt might be use with, but I assume they could be gigantic. But anyway, does multiple opening and closing a file might be a performance issue for any of vt usage scenarios? I didn't do any benchmark, but I found this -> https://stackoverflow.com/questions/26250744/efficiency-of-fopen-fclose/26251167 and it shows that on some machine (2.2GHz Core i7, 8GB of RAM running OS X) opening and closing a file 100000 times takes about 0.041s. I can imagine that generally vt would be used on enormous clusters, so opening/closing a file is negligible regardless of how many times it's done, but I just want to make sure.

**Comment by lifflander** [comment]
@nlslatt @jstrzebonski I think we want to port this to the release branch.
