### ISSUE TITLE
Add a collective broadcast call for collections

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1024]
**What Needs to be Done?**

Currently, if a user does `proxy.broadcast<MyMsg, &MyCol::handler>()` it is a rooted call that only one rank should invoke if a single broadcast is the intention. However, for more SPMD programs, often every node might know and want to participate in the broadcast, which can make it significantly cheaper (a simple local traversal). This also might make sense in the context of chainsets with more SPMD-like style. 

Maybe we can call it `proxy.broadcastCollective` although that seems a little long. @PhilMiller ideas on a good name of this?

**Comment by PhilMiller** [comment]
I think that's probably the right name, given naming conventions in the rest of the system.

It may be somewhat unfortunate, in that in the long run, we maybe expect the collective versions of many things to be the default; they're potentially more efficient if the control flow allows for their use, and they don't require a surrounding `if (node == 0) { }`  block.

Should we start moving toward explicitly naming both `fooRooted` and `fooCollective`, and plan to assess which one gets more use over time?

**Comment by lifflander** [comment]
Yes, I think that's a good idea to start explicitly naming them like that.

**Comment by lifflander** [comment]
@JacobDomagala Phil and I discussed this and we want to continue with the local delivery without any coordination.
