### ISSUE TITLE
Add commit check for "Fixes #issue" in comment

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1031]
**What Needs to be Done?**

If a PR is created, users should normally annotate that PR as it fixes an issue so the issue automatically closes when the PR is merged. However, it's easy to forgot to add that to the comment.

Write a PR hook (like the issue style checks) that greps for that in the issue comment so we can inform the user if they forgot.

You can probably model it after the commit check hook, that I've developed in this repo: https://github.com/DARMA-tasking/check-commit-format

**Comment by PhilMiller** [comment]
Is the PR description available to the hooks? The relevant line won't necessarily appear in a commit message

**Comment by lifflander** [comment]
Yes, the PR description to the workflow. The code to get it will look something like:
```
contains(${{ github.event.issue.body}}, 'Fixes')
```
