### ISSUE TITLE
Argument parsing error unconditionally triggers MPI_Init

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1069]
**Describe the bug**
When an invalid command-line argument is passed to vt, it calls `MPI_Init` (`src/vt/runtime/runtime.cc:153`) in the process of handling the error.  This is problematic when vt is used within EMPIRE because MPI was already initialized.

**To Reproduce**
1. Call MPI_Init in your driver before initializing vt
2. Pass an invalid command-line argument to your executable

**Expected behavior**
If MPI was already initialized, it should use the existing communicator.

**Comment by pnstickne** [comment]
@nlslatt With current updates, it will no longer do an MPI_Init. However, it will STILL cause an MPI_Abort & program termination.

Is this termination (without 'random crash') still an issue for the use-case?

**Comment by lifflander** [comment]
> @nlslatt With current updates, it will no longer do an MPI_Init. However, it will STILL cause an MPI_Abort & program termination.
> 
> Is this termination (without 'random crash') still an issue for the use-case?

Yes, I believe that was the use case. We want an readable error if the options are specified incorrectly so we can solve the problem without digging.

**Comment by nlslatt** [comment]
> @nlslatt With current updates, it will no longer do an MPI_Init. However, it will STILL cause an MPI_Abort & program termination.
> 
> Is this termination (without 'random crash') still an issue for the use-case?

Sorry, I missed this notification.  It's appropriate to terminate in my use case, as long as it announces the reason for the termination (unrecognized command-line argument) first.
