### ISSUE TITLE
Trim down test_term_dep test down to reduce timeouts

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1070]
**What Needs to be Done?**

Currently, on 4 processors, test_term_dep is timing out. Reduce the iterations so it doesn't timeout as easily.

**Comment by lifflander** [comment]
Actually I think this might be a bug/hang in the test. It runs in ~6 seconds on 4 processors on my Mac. Unless the cluster is vastly slower, I don't think it should take that long.

**Comment by pnstickne** [comment]
This shouldn't take so long. Bug resolved in #1074

**Comment by lifflander** [comment]
I'm still seeing this hang

**Comment by pnstickne** [comment]
I'm not seeing any timeouts :-/

**Comment by lifflander** [comment]
I don't think this is an issue anymore
