### ISSUE TITLE
nvcc sees multiple -std=c++* options, and complains

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#1090]
**Describe the bug**
Every file compiled with nvcc (as in the 10.1 or 11.0 CI builds) emits this warning:
```
nvcc_wrapper - *warning* you have set multiple standard flags (-std=c++1* or --std=c++1*), only the last is used because nvcc can only accept a single std setting
```

**Comment by pnstickne** [comment]
IIRC, this has to do with the flag added manually and the flag from the cmake options.

**Comment by PhilMiller** [comment]
Is there a way we can tell cmake to just give us the right flag, and not manually add one?

**Comment by lifflander** [comment]
Btw, I believe that EMPIRE has the same problem even without VT.

**Comment by lifflander** [comment]
This is fixed
