### ISSUE TITLE
Enable assertions during CI when release builds are used

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1098]
Right now, if you build with cmake in release mode, assertions `vtAssert*()` are disabled. Since the workflows all build in release to reduce memory usage, we don't see if assertions are breaking. I believe the configuration parameter `vt_check_enabled(production)` is used to switch between assertion failures breaking or not in release mode. 

Add a cmake option to control this so we can have assertions in release builds in the workflows.

**Comment by JacobDomagala** [comment]
Reopened after comment https://github.com/DARMA-tasking/vt/pull/1107#discussion_r504063326
