### ISSUE TITLE
Reductions are leaking over phases

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1116]
**Describe the bug**
Here is a screenshot of the stack trace from heaptrack:

<img width="1779" alt="Screen Shot 2020-10-12 at 11 03 14 AM" src="https://user-images.githubusercontent.com/3324465/96018211-cf429180-0dff-11eb-971f-6fa77c64719e.png">

**Comment by PhilMiller** [comment]
Does this happen on the release branch, or only `develop`?

**Comment by lifflander** [comment]
> Does this happen on the release branch, or only `develop`?

Only on develop.

**Comment by nlslatt** [comment]
I think the data structure that is still growing is `vt::collective::reduce::Reduce::next_seq_for_tag_`.  I don't see any code that cleans up sequential IDs.  Where/when would be safe to do that?

**Comment by lifflander** [comment]
I don't think this is actually a problem anymore. I'm going close it. @nlslatt If you know this is still a problem please re-open.
