### ISSUE TITLE
ElementStats is leaking memory from previous phases

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1122]
**Describe the bug**
`ElementStats` inside collection elements is leaking memory.

**Comment by jstrzebonski** [comment]
@lifflander could you describe the problem a bit more indepthly? I tried to run all tests and examples with LeakSanitizer, but didn't get anything usefull, and also running examples/collection with Valgrind didn't give me much :'- (

**Comment by PhilMiller** [comment]
It's not leaking, it's just accumulating. We need to coordinate between @jstrzebonski and @nlslatt to avoid duplicate efforts

**Comment by nlslatt** [comment]
@jstrzebonski I'll take care of this today.
