### ISSUE TITLE
runInEpoch* do not take a universal reference (they take a r-val ref)

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1125]
**What Needs to be Done?**

Due to this, you can pass an existing std::function to them. Template them and move to the header file. Something like this would work:

```C++
template <typename Callable>
void runInEpochCollective(Callable&& fn) {
  //...
}
```

**Comment by lifflander** [comment]
Also, write tests for these to avoid problems like this coming up

**Comment by cz4rs** [comment]
> Due to this, you **can** pass an existing std::function to them. Template them and move to the header file. Something like this would work:

Changes implemented, typo in the description? (it was **not** possible to pass std::function before and it is possible now, after templating the functions)
