### ISSUE TITLE
Add additional checkpoint documentation

### ISSUE THREAD

**Issue by uhetmaniuk** [DARMA-tasking/vt#1151]
**What Needs to be Done?**

- [x] Insert partial checkpoint documentation

**Comment by cz4rs** [comment]
revisited: verify checkpoint documentation and see if this is still needed

**Comment by cz4rs** [comment]
current status for reference (`develop`):
![image](https://user-images.githubusercontent.com/4639165/116198114-dc88f300-a735-11eb-93d5-5c57a32bfac6.png)
