### ISSUE TITLE
Load models see permanent IDs in stats data

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1153]
**Describe the bug**
The `RawData` load model gets a map covering multiple phases from `NodeStats`.  For the current phase, the stats for objects are keyed on the temporary ID.  However, for older phases, they are keyed on permanent IDs.  This causes exceptions to be thrown by the map when LB is invoked with a load model needing stats from more than one phase (like `PersistenceMedianLastN`).  A new test is needed for demonstrating this problem.

**Comment by lifflander** [comment]
@nlslatt Is this still an issue that needs fixing?

**Comment by nlslatt** [comment]
@lifflander It's certainly not an issue on develop.  Are we still maintaining the old release branch?  I'd have to check to see if it's still a problem there.

**Comment by nlslatt** [comment]
Now that our release branches are based off develop, this is not relevant.
