### ISSUE TITLE
ZoltanLB uses deprecated sends

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1157]
**Describe the bug**
ZoltanLB uses deprecated sends and needs to be updated to use the current interface.

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by lifflander** [comment]
Can you look through this?
