### ISSUE TITLE
Add -Werror for CI builds that are warning clean

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#1201]
**What Needs to be Done?**

- [ ] Check which compiler versions in CI builds don't generate any warnings
- [ ] Add `-Werror` to the build configuration / scripts for those builds

**Is your feature request related to a problem? Please describe.**

The codebase should progressively become more warning-clean, and stay that way for settings that it already achieves that.

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by cz4rs** [comment]
for reference similar work done in `checkpoint` (configurable per build, off by default):
https://github.com/DARMA-tasking/checkpoint/pull/140/commits/ef777101049abb420fe3d5fc96345abf2e181634
