### ISSUE TITLE
handle errors correctly when reading files in StatsRestartReader

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#1213]
**Describe the bug**
Warnings related to unused return values from `fscanf` calls in `stats_restart_reader.cc` were silenced, but the code still lacks correct logging and error handling.

**Expected behavior**
Handle malformed records / files correctly. Make sure to unit test these edge cases.

**Comment by lifflander** [comment]
This is fixed due to the new json LB stats. Closing the issue.
