### ISSUE TITLE
Explore enabling debug prints in release builds and assertions

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1229]
Create multiple levels of debug prints. First level can be enabled in release.

Terse, normal, verbose

**Comment by lifflander** [comment]
`--vt_debug_verbose`

**Comment by cz4rs** [comment]
TODO:
Apart from the general mechanism (terse, normal, verbose), all existing prints must be categorized.
`--vt_help` produces following list of debug flags (matching components):

- [ ]   --vt_debug_gen            
- [ ]   --vt_debug_runtime      
- [ ]   --vt_debug_active         
- [ ]   --vt_debug_term           
- [ ]   --vt_debug_termds       
- [ ]   --vt_debug_barrier        
- [ ]   --vt_debug_event          
- [ ]   --vt_debug_pipe            
- [ ]   --vt_debug_pool            
- [ ]   --vt_debug_reduce     
- [ ]   --vt_debug_rdma        
- [ ]   --vt_debug_rdma_channel   
- [ ]   --vt_debug_rdma_state       
- [ ]   --vt_debug_param         
- [ ]   --vt_debug_handler       
- [ ]   --vt_debug_hierlb          
- [ ]   --vt_debug_gossiplb      
- [ ]   --vt_debug_scatter        
- [ ]   --vt_debug_sequence   
- [ ]   --vt_debug_sequence_vrt   
- [ ]   --vt_debug_serial_msg       
- [ ]   --vt_debug_trace          
- [ ]   --vt_debug_location      
- [ ]   --vt_debug_lb              
- [ ]   --vt_debug_vrt             
- [ ]   --vt_debug_vrt_coll      
- [ ]   --vt_debug_worker       
- [ ]   --vt_debug_group         
- [ ]   --vt_debug_broadcast  
- [ ]   --vt_debug_objgroup    
- [ ]   --vt_debug_phase        
- [ ]   --vt_debug_print_flush 

These could be assigned further to make sure that correct levels were used for each print.

**Comment by jstrzebonski** [comment]
I don't know if we're open to using an additional library for logging, but if so, there's a `spdlog`
https://github.com/gabime/spdlog

**Comment by cz4rs** [comment]
> I don't know if we're open to using an additional library for logging, but if so, there's a `spdlog`
> https://github.com/gabime/spdlog

looks good, both basic usage and some features that we might want to add eventually
