### ISSUE TITLE
%25 in Azure CI warning

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1243]
**What Needs to be Done?**

```
##[warning]%25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
```

**Comment by lifflander** [comment]
Example: https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=5046&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c

**Comment by cz4rs** [comment]
Related (seems like a bug in `azure-pipelines-tasks`):
https://github.com/microsoft/azure-pipelines-tasks/issues/14302

**Comment by anthraxn8b** [comment]
This is polluting the build job log! Please fix it asap! THX!

**Comment by cz4rs** [comment]
> This is polluting the build job log! Please fix it asap! THX!

The original issue is located in `azure-pipelines-tasks` repository - maybe that is where your comment was supposed to land?

**Comment by jstrzebonski** [comment]
According to https://github.com/microsoft/azure-pipelines-tasks/issues/14302 it's fixed.
And I cannot find this warning in logs anymore, so I'm closing the issue.
