### ISSUE TITLE
Unify re-construction logic for collection elements with checkpoint

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1244]
**What Needs to be Done?**

Right now, in MigrateMsg, we just `new ColT{}` without following checkpoint's reconstruction logic. Use that interface to unify it with reconstruction.

**Comment by lifflander** [comment]
@JacobDomagala Can you look at this? I think this might be done already.

**Comment by JacobDomagala** [comment]
Fixed with https://github.com/DARMA-tasking/vt/pull/1280
