### ISSUE TITLE
fields omitted during serialization

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#1258]
**Describe the bug**
Multiple fields are not serialized during either footprinting or regular serialization. Add missing fields to `serialize` methods.
Note: this should be safe for all of footprinting, caution is required for serializers used in other modes.

**To Reproduce**
See [serialization sanitizer run over `vt`](https://github.com/DARMA-tasking/serialization-sanitizer/actions?query=workflow%3A%22PR+tests+%28vt%2C+clang-5.0%2C+ubuntu%29%22).

**Comment by lifflander** [comment]
I think something must be wrong.. I doubt that all of those are not serialized.

**Comment by cz4rs** [comment]
> I think something must be wrong.. I doubt that all of those are not serialized.

I am fixing the false positives right now, correct number of results should be below 50.
