### ISSUE TITLE
Release build system does not find deps in lib

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1274]
**Describe the bug**
The vt release branch doesn't find checkpoint or detector when dropped into `vt/lib/` because of `PROJECT_LIB_DIR ` being set too late in the root `CMakeLists.txt` file.

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by lifflander** [comment]
Closing as this is fixed
