### ISSUE TITLE
Remove dead line of code vrt/collection/manager.impl.h:2935

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1292]
**What Needs to be Done?**

This line of code seems to do nothing. Let's remove it.
```C++
  CollectionProxy<ColT, IndexT>(proxy).operator()(idx);
```

**Comment by PhilMiller** [comment]
Have you tried `git blame` on it and walking its history? That reads like something meant to ensure type usability.

**Comment by lifflander** [comment]
Yes, I did. @nlslatt changed the line in March 3rd, 2019. It used to save the return value from this line, which was unused (probably due to other code changes). The quick fix was to just not save the return value, but that doesn't really make sense since the operation is stateless.
