### ISSUE TITLE
Develop a set of performance tests that we can graph to track VT performance

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1294]
**What Needs to be Done?**

Let's discuss benchmarks we would like to see as part of a suite of performance tests that we run on VT develop after each merge

**Comment by cz4rs** [comment]
An example of a memory bug that was detected late in `checkpoint`: https://github.com/DARMA-tasking/checkpoint/issues/180 (`std::unordered_map::rehash`).
Existing unit tests just verify the correctness of code, but don't track the (heap) memory usage.

**Comment by cz4rs** [comment]
Currently existing performance tests are at `vt/tests/perf`. They seem to be referenced in `vt/tests/CMakeLists.txt`:
https://github.com/DARMA-tasking/vt/blob/a2f5914daf3b08686b73730e087ef6aeb5425363/tests/CMakeLists.txt#L188-L207
but they are not actually built.

First step could be to get them running in CI with something as simple as https://github.com/sharkdp/hyperfine, and then build on top of it considering memory consumption, container isolation, more advanced scenarios.

**Comment by cz4rs** [comment]
Possibly related: https://github.com/DARMA-tasking/vt/issues/245.

**Comment by lifflander** [comment]
@JacobDomagala Please write performance test harness.
