### ISSUE TITLE
Never run load balancer on first phase

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1296]
**What Needs to be Done?**

**Comment by nlslatt** [comment]
@lifflander When LB is specified using an interval instead of a config file, should we just run LB on `(phase - 1) % interval == 0` instead of `phase % interval == 0`?

**Comment by lifflander** [comment]
> @lifflander When LB is specified using an interval instead of a config file, should we just run LB on `(phase - 1) % interval == 0` instead of `phase % interval == 0`?

Yes, I think so. I think that "never" was too strong.. just don't do it by default unless explicitly turned on the first phase in the LB config file

**Comment by PhilMiller** [comment]
I think the comparison we want is more like `phase % interval == 1 || (interval == 1 && phase != 0)`. Offsetting `phase` that way means we'll wait almost a full `interval` worth of phases before running LB once (and, have to think about modulo behavior with negative numbers).

**Comment by nlslatt** [comment]
Why would what I proposed make it wait almost a full interval?  When `phase == 1`, `phase-1 == 0`.

**Comment by nlslatt** [comment]
If we deliberately set the interval to 1, is it actually appropriate to skip LB on phase 0?

**Comment by PhilMiller** [comment]
Oops, you're right. I was thinking more about the behavior on `phase == 0`
