### ISSUE TITLE
Collection insertions are non-idempotent after migration

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1300]
**What Needs to be Done?**

bvh does multiple insertions of the same index expecting them to be idempotent. This works out if the load balancer doesn't run because it does a local check to ensure not to insert multiple times. However, with the load balancer, two copies of the element end up existing causing a crash.

The solution is to query the home node to ensure that the insertion has not happened already, even if the insertion is off home (the user is allowed to insert wherever they desire).

**Comment by PhilMiller** [comment]
This was the exact use case for "demand creation" in Charm++ with `createhere` and `createhome` attributes for handlers. You don't even explicitly insert the object, you just send a message to the index that should receive it, and the collection manager makes sure it exists.

**Comment by lifflander** [comment]
I think calling `insert` is fine.. we just need to make sure even with potential race conditions it never inserts twice

**Comment by lifflander** [comment]
@nmm0 The problem currently is that it's not talking to the home before doing the insertion. So you can get multiple insertions if you target different nodes or the LB runs and the element is no longer local. The latter case is what bvh is failing with.
