### ISSUE TITLE
Run tests on single Node

### ISSUE THREAD

**Issue by JacobDomagala** [DARMA-tasking/vt#1328]
Currently the minimum amount of nodes used for tests is 2 (on the machine with 4 processors we run on 2/4 nodes, on the machine with 2 processesors, such as our pipelines, we run only on 2 nodes). 
Change CMake to also run them on single node and disable/skip the ones that require at least 2 nodes. 

This is part of https://github.com/DARMA-tasking/vt/issues/1297

**Comment by cz4rs** [comment]
Possibly related: https://github.com/DARMA-tasking/vt/issues/415.
