### ISSUE TITLE
Have MsgSharedPtr capture the size of the message before erasing type

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1344]
**What Needs to be Done?**

Originated from this comment: https://github.com/DARMA-tasking/vt/pull/1322#discussion_r599014853

Should simplify the active messenger quite a bit so the size doesn't have to be passed around everywhere. Need to make sure that `MsgSharedPtr<T>` is constructed from the correct non-erased type everywhere it is used

**Comment by PhilMiller** [comment]
The implementation in progress seems to be headed toward recording the message size in a field in the message envelope, rather than the smart pointer. That could work, but there may be concerns about occupying additional space in the message that might not be necessary.

**Comment by MikolajZuzek** [comment]
(work in progress)

## Message routing

1. User calls "interface" methods (marked with orange): `ActiveMessanger::sendMsg()`, `ActiveMessanger::broadcastMsgAuto()`, etc.;
2. Calls are routed through implementation helpers to produce `PendingSend` instance;
3. `sendMsg()` is called on `PendingSend` instance, which triggers `ActiveMessanger::doMessageSend()`;
4. Implementation helpers under `doMessageSend()` trigger `RunnableNew::send()` which dispatches the call along all registered contexts.

![sendMsg uml](https://user-images.githubusercontent.com/29018159/117842404-2f0df780-b27e-11eb-9fd0-ef0f64e58251.png)

## Message size considerations

1. Default size is derived from message type - `sizeof(MsgT)`;
2. User can set message size explicitly with methods like `makeMessageSz()`, `sendMsgSz()` or `broadcastMsgSz()`;
3. Serialized messages are sized automatically with `vt::serialization::MsgSizer<T>::get()`;
4. Size can be "augmented" - like with combining base size and put size for `vt::PutEnvelope` in `ActiveMessenger::sendMsgBytesWithPut()` (see [vt/messaging/active.cc:235](https://github.com/DARMA-tasking/vt/blob/develop/src/vt/messaging/active.cc#L233-L252))
4. On _runnable_ side, `LBStats` is now the only context that overrides `send()` (it passes message size in a call to `ElementStats::recvToNode()` without the need for actual message).
