### ISSUE TITLE
PR comment doesn't show compilation error in case of gcc-7 "No space left on device" error

### ISSUE THREAD

**Issue by jstrzebonski** [DARMA-tasking/vt#1357]
Example in PR https://github.com/DARMA-tasking/vt/pull/1356

![image](https://user-images.githubusercontent.com/14062470/113298954-a73ae200-92fc-11eb-9e88-b07deb0d82f7.png)

![image](https://user-images.githubusercontent.com/14062470/113299063-c33e8380-92fc-11eb-9b8f-bd6427bab803.png)

**Comment by nlslatt** [comment]
I'm also seeing reported successes for cases where Docker is down.  The error that wasn't caught when making the PR comment was:

```
ERROR: for ubuntu-cpp-clean  received unexpected HTTP status: 503 Service Unavailable
received unexpected HTTP status: 503 Service Unavailable
```

This is from https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=13585&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=1364e02f-4e1e-51cf-2821-fd252a3c0e34&l=13
