### ISSUE TITLE
Remove old circleCI folder, ensure that all integrations are active and remove old ones (including Zenhub)

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1416]
**What Needs to be Done?**

- [ ] First do this
- [ ] Then do that.
- [ ] Also this other thing.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by jstrzebonski** [comment]
Done.
