### ISSUE TITLE
Message ref-count limit triggers in simple cases

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1423]
**Describe the bug**
When running `lb_iter`, I'm getting this assertion when I set the number of elements high enough:

```
vt: [0]              Reason: Bad ref-count on message ref-increment. Message ref-count must never be negative and cannnot exceed limit (100).
vt: [0]    Assertion failed: (envp->ref >= 0 and envp->ref < 100)
vt: [0]                Node: 0
vt: [0]           Num Nodes: 2
vt: [0]                File: /Users/nlslatt/work/vt/vt-tmp/src/vt/messaging/envelope/envelope_ref.impl.h
vt: [0]                Line: 68
vt: [0]            Function: envelopeRef
vt: [0]                Code: 1
```

I've seen this with GossipLB and RandomLB.  I haven't tried other LBs.

**To Reproduce**

`mpirun -np 2 ./examples/collection/lb_iter 200 1 5 --vt_lb --vt_lb_interval=1 --vt_lb_name=RandomLB`

or

`mpirun -np 2 ./examples/collection/lb_iter 200 1 5 --vt_lb --vt_lb_interval=1 --vt_lb_name=GossipLB`

Reducing the number of elements from 200 to 100 does not trigger the assertion.  This is on my Mac.

**Comment by lifflander** [comment]
@nlslatt Actually this might make sense because during a broadcast does each element hold a reference to the message?

**Comment by nlslatt** [comment]
@lifflander You could be right.  The backtrace shows it being within a broadcast.

I can reproduce it more simply with:

`mpirun -np 1 ./examples/collection/lb_iter 96 1 5 --vt_lb --vt_lb_interval=1 --vt_lb_name=RandomLB`

With 95 elements instead of 96, it doesn't fail the assertion.

**Comment by nlslatt** [comment]
@nmm0 I want to make sure you're aware of this because it might impact how you're interpreting the high ref counts in your app.
