### ISSUE TITLE
Fix issue with tests that timeout on Azure

### ISSUE THREAD

**Issue by JacobDomagala** [DARMA-tasking/vt#1427]
After merging https://github.com/DARMA-tasking/vt/pull/1414 some Azure pipelines started to fail with test timeouts errors:
```
488 - vt:*/TestSequencerExtensive.test_wait_1/*_proc_2 (Timeout)
554 - vt:*/TestTermDepSendChain.test_term_dep_send_chain/*_proc_2 (Timeout)
```

See if changes introduced with #1414 are the cause of it. If not, and it's the issue with azure pipelines, then we might want to increase the timeout limit for tests (temporarily?)

**Comment by MikolajZuzek** [comment]
Would it be possible to make test timeout configurable ?

It's now fixed to 60s (see [_tests/CMakeLists.txt:106_](https://github.com/DARMA-tasking/vt/blob/develop/tests/CMakeLists.txt#L106)) and seem to override `ctest --timeout` option, which makes the tests very fragile. For instance they'll fail with timeouts _when the platform is busy_ or when _running in parallel_ with (e.g. with `ctest -j 16`).
