### ISSUE TITLE
codacy fails when the target branch is not `develop`

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#1433]
`Codacy Static Code Analysis` fails for PRs targeting `1.0.2-proposed-update` branch (see #1418 for an example, the same for #1367 targeting `master`).

```
Seems like the 1.0.2-proposed-update is not being analyzed. To review this pull request enable the branch in the repository settings.
```

@jstrzebonski Can you have a look if this can be enabled for more branches?

**Comment by jstrzebonski** [comment]
Another example: https://github.com/DARMA-tasking/vt/pull/1441

**Comment by jstrzebonski** [comment]
Fixed.
