### ISSUE TITLE
Print time units and adjust accordingly for LB times

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1435]
**What Needs to be Done?**

On the LB statistics line that prints info after LB runs, print the time units that we using. Automatically adjust the units depending on how large the quantities are (seconds vs milliseconds), etc.

**Comment by cz4rs** [comment]
Related line:
https://github.com/DARMA-tasking/vt/blob/f7cbf2beb07ed64de2692525ae9721e6e4cfcb3e/src/vt/vrt/collection/balance/baselb/baselb.cc#L244

Current output:
```
vt: [0] (t) lb: BaseLB::finalize: LB total time=0.0006918907165527344, total migration count=45
```

**Comment by PhilMiller** [comment]
Before we plow ahead with this, I want to check whether scaling the units as they're printed is really desirable. It will make scripted processing much more difficult.

@nlslatt

**Comment by PhilMiller** [comment]
I could get behind printing them in scientific notation, maybe with the exponent pinned to multiples of 3

**Comment by PhilMiller** [comment]
Maybe something like https://github.com/martinmoene/EngFormat-Cpp
