### ISSUE TITLE
Handle exceptions thrown inside scheduler loop

### ISSUE THREAD

**Issue by JacobDomagala** [DARMA-tasking/vt#1443]
https://github.com/DARMA-tasking/vt/issues/1394 added new build option to throw an exception on `vtAbort`. This introduces a new issue, when an exception is thrown inside scheduler loop the traces are not handled correctly. 
```c++
void runSchedulerWhile(...) {
   triggerEvent(SchedulerEventType::BeginSchedulerLoop);
   
   while (cond()) {
      // throw here
      runSchedulerOnceImpl();
   }
   triggerEvent(SchedulerEventType::EndSchedulerLoop);
```

*What needs to be done*
Either create RAII object, which triggers BeginSchedulerLoop and EndSchedulerLoop or wrap the runSchedulerOnceImpl with try-catch block

**Comment by lifflander** [comment]
Let's discuss exceptions in an upcoming meeting to determine the direction we want to go with this.
