### ISSUE TITLE
TemperedLB threshold is inappropriate

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1460]
**Describe the bug**
The threshold used for determining whether to skip running `TemperedLB` is inappropriately low.  The current code essentially boils down to:

```
static constexpr double const tolerance = 0.05f;
auto const avg  = stats.at(lb::Statistic::P_l).at(lb::StatisticQuantity::avg);
auto const max  = stats.at(lb::Statistic::P_l).at(lb::StatisticQuantity::max);
should_lb = max > tolerance * avg;
```

Because the tolerance is less than 1, `should_lb` will always be true.  The intended value was likely `1.05f`.

**Comment by nlslatt** [comment]
This probably should be made an LB arg so it can be tuned for the application.

**Comment by lifflander** [comment]
There is a broader issue related to https://github.com/DARMA-tasking/vt/issues/788 that we want to be able at a high level to control when LB runs based on the expected value we will get from running.
