### ISSUE TITLE
Create an RAII interface for epochs (collective/rooted)

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1476]
**What Needs to be Done?**

- [ ] Create an alternative interface using RAII rather than push/popEpoch

**Comment by nmm0** [comment]
Design:
* Similar to std::lock_guard
* should release of the RAII epoch also call finishedEpoch? no
* Multiple epochs? no
* no_epoch? error on this; global: use like normal

Tasks:
- [ ] Implemantation
- [ ] Use in CollectionManager
- [ ] Add tests
- [ ] Update documentation. This API should be preferred
