### ISSUE TITLE
Explore new CI pipeline to test Intel compilers on Sandia resources

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1496]
**What Needs to be Done?**

Figure out a cdash pipeline with Jenkins to Sandia machines.

**Comment by cz4rs** [comment]
Useful documentation:
- https://www.jenkins.io/doc/book/pipeline/getting-started/
- https://www.jenkins.io/solutions/github/
- https://blog.kitware.com/github-checks-and-statuses-from-cdash/

Kokkos' Jenkinsfile:
- https://github.com/kokkos/kokkos/blob/master/.jenkins

**Comment by lifflander** [comment]
This is in progress so I'm closing this issue now.
