### ISSUE TITLE
Add function to extract local indices from VT for collections

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1497]
**What Needs to be Done?**

- [ ] First do this
- [ ] Then do that.
- [ ] Also this other thing.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
This was a topic of somewhat extended discussion in Charm++, due to certain semantic issues it presents. We should at least read through their relevant issue
