### ISSUE TITLE
Spack package build failing due to cmake changes

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1519]
**Describe the bug**
Take a look at [this](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=20637&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2) build, which is failing now. `vt-sample-project` was changes to import projects as subdirectories. It looks like the new symbolic link command in the sample project is failing due to a cmake versioning problem?

**Comment by jstrzebonski** [comment]
Is blocked by  DARMA-tasking/vt-sample-project#5
