### ISSUE TITLE
Infrastructure failure (on Azure) should not fail job

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1523]
**Describe the bug**
A failure to update the cache in Azure after a pipeline runs is causing the job to report failure. Any infrastructure failures shouldn't cause the job to fail if the tests actually ran correctly:
<img width="1021" alt="Screen Shot 2021-08-17 at 10 42 49" src="https://user-images.githubusercontent.com/3324465/129775311-a24c29c3-d575-45b5-919f-5272385de097.png">

https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=20803&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=db4f6312-f132-4162-af62-e3c844cdd606

**Comment by PhilMiller** [comment]
Neither retrieving the cache before the job, nor updating it afterward
