### ISSUE TITLE
Compute LB statistics on every phase

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1559]
Currently, vt only prints LB statistics after a phase if load balancing was requested then.  The pre-LB statistics are computed accurately but the post-LB statistics are estimates provided by the load balancer.  Computing LB statistics after each phase, not just the LB ones, would let us see the true impact of load balancing and how the imbalance evolves with phase when the load balancer has not been re-run.

**What Needs to be Done?**
~~Add a dummy load balancer to trigger the LB statistics reductions even when load balancing is not used.  This will be on by default but can be disabled with a command-line argument.~~

**Comment by PhilMiller** [comment]
Would it make sense to separate stats gathering and printing from actual execution of *any* LB strategy? The basic stats themselves are not really something the strategies should have to come up with individually.

**Comment by nlslatt** [comment]
> Would it make sense to separate stats gathering and printing from actual execution of _any_ LB strategy? The basic stats themselves are not really something the strategies should have to come up with individually.

The stats come from `BaseLB`.  That logic is skipped when `NoLB` is selected because no load balancer is constructed.  How does that affect your opinion?

**Comment by nlslatt** [comment]
> Would it make sense to separate stats gathering and printing from actual execution of _any_ LB strategy? The basic stats themselves are not really something the strategies should have to come up with individually.

When I mentioned estimates from the LB strategy, I meant that the strategy modifies data members in `BaseLB` that track the processor load.  That data member is fed into the reductions, both pre- and post-LB.

**Comment by nlslatt** [comment]
There are several closely coupled limitations that we should consider together when deciding on a path forward:
-	Post-LB object statistics reduction races with migration, operating on cached pre-LB loads stored in pre-LB locations; therefore, nothing new is gained from running the so-called post-LB reduction. Load models that require information from the collection element itself may find that the object is no longer available at post-LB reduction time. This relates to #1295 and impacts #1265.
-	Post-LB processor statistics reduction races with migration, operating on cached pre-LB processor loads that may or may not have been updated to reflect migrations planned by the load balancer; therefore, the reported post-LB statistics can completely ignore planned migrations, represent them only approximately, or represent them exactly. This relates to #1522.
-	Computing the object and processor statistics even when LB isn’t run allow the user to better understand when/how often to run the LB as well as allow vt to decide on the fly whether or not to run LB. This relates directly to this issue, #1559.
-	Load models that require more than a single phase of history (like PersistenceMedianLastN) have insufficient history post-migration for recomputing processor loads. This relates to #1127 and may also impact dynamic collections.
-	It may be possible to remove object stats when objects emigrate and add them when objects immigrate; however, any updates to the StatsData instances to track migrations for facilitating correct post-LB statistics computation will break correctness of dumping object stats to the json files due to the ordering of these operations. Is there a reason why dumping of object stats needs to come after migration and not before?
-	Object subphase loads are completely ignored when computing object statistics, but might be relevant for understanding performance.
-	Object subphase loads currently must be reduced to a single scalar load before processor-level statistics are computed; this limits what a load balancer knows about the system it is required to balance.
-	It would be preferable to have the load balancers be pure functions that can be called, having the LB manager handle migrations and object statistics reductions instead of BaseLB.
-	We may want to combine all reductions that happen near the same point in time instead of running them in separately.

**Comment by nlslatt** [comment]
@lifflander @PhilMiller I'm starting to think about making the load balancers pure functions like you suggested, but I'm seeing potential issues.  The load balancers are object groups right now and use that for communicating across ranks.  Are you envisioning a solution where the LB is truly just a function, or did you just mean that an LB should only return a set of suggested migrations and never directly trigger any state changes?

**Comment by nlslatt** [comment]
We've been computing LB statistics on every phase for a while now.
