### ISSUE TITLE
Create new load model for proposed migrations

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1569]
**What Needs to be Done?**

Related to issue comment https://github.com/DARMA-tasking/vt/issues/1559#issuecomment-928354276. We want to create a load model that can track proposed migrations and can be used to compute a reduction to determine the quality of LB after those proposed migrations take place.

**Comment by nlslatt** [comment]
@PhilMiller You might find https://github.com/DARMA-tasking/vt/issues/1568#issuecomment-931638064 helpful for planning.
