### ISSUE TITLE
Read in communication data from json files

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1589]
Presently, the constructor of `NodeStats`, which reads from json files, does not populate any communication data. The subphase communication is neither dumped nor read by `NodeStats`.

**What Needs to be Done?**
[ ] Have the constructor read the full-phase communication and populate the `node_comm_` member.
[ ] Add a test that populates a `NodeStats` object, dumps json from it, constructs a new `NodeStats` object from the json file, and then compares the two.

Should we do anything with the subphase communication at this point?

**Comment by lifflander** [comment]
I don't think that any of the  communication is being stored by subphase at this point.
