### ISSUE TITLE
Update clang-format file

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#1592]
**What Needs to be Done?**

- [ ] Fix clang-format identing of preprocessor directives
- [ ] Make clang-format negatively indent access specifiers

**Comment by jstrzebonski** [comment]
@nmm0

Nick, for access modifiers `AccessModifierOffset` needs to be changed to `-2`.

About the preprocessor directives indention, what style is correct? Take a look at paragraph `IndentPPDirectives` here: https://clang.llvm.org/docs/ClangFormatStyleOptions.html, basically:

`None`:

```cpp
#if FOO
#if BAR
#include <foo>
#endif
#endif
```

`AfterHash`:

```cpp
#if FOO
#  if BAR
#    include <foo>
#  endif
#endif
```

`BeforeHash`:

```cpp
#if FOO
  #if BAR
    #include <foo>
  #endif
#endif
```

Currently we have `BeforeHash`.
