### ISSUE TITLE
Create 1.1.1 v5 RC

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1597]
**What Needs to be Done?**

- [ ] First do this
- [ ] Then do that.
- [ ] Also this other thing.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
#1585 #1595 are the two target PRs I'm aware of

**Comment by cz4rs** [comment]
PR is merged and the release (https://github.com/DARMA-tasking/vt/releases/tag/1.1.1-beta.5) is ready - closing.
