### ISSUE TITLE
Associate collection proxy with CollectionChainSet to automatically track indices

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1660]
**What Needs to be Done?**

One of the motivations for this is bvh's insertable collections, so we can track the indices that exist without manually hooking into the constructor/destructor/migration hooks. We also want to provide a enum to either track the local indices or the home indices. By default, we want this to be the local indices for performance reasons.

**Comment by PhilMiller** [comment]
This would also replace manual coupling code in EMPIRE
