### ISSUE TITLE
Support HIP equivalent for AsyncOpCUDA

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#1671]
**What Needs to be Done?**

- [ ] First do this
- [ ] Then do that.
- [ ] Also this other thing.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
Relevant functions documented here: http://rocm-developer-tools.github.io/HIP/group__Event.html

**Comment by nlslatt** [comment]
@JacobDomagala I'm working on getting access to a machine where I can test this. Please put up a draft PR (no rush) and I should be able to do that when I'm back from my vacation.
