### ISSUE TITLE
Stop using cmake code to generate git header information about sha, etc.

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1677]
**What Needs to be Done?**

This causes cmake to run every time something changes at all. We want to just add a custom command that updates a cc file that is linked into the VT library that contains only the SHA (not the description or whether it is dirty or not).

**Comment by PhilMiller** [comment]
Only update the .cc file if the contents to be written in it have changed

**Comment by lifflander** [comment]
@nmm0 When do you think you can work on this? I would like to get this in the next beta release if possible.
