### ISSUE TITLE
Create `1.1.1 beta v7` release candidate

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1679]
**What Needs to be Done?**

- [x] Check why `main` appears to be ahead of `develop`
- [x] Create PR (`develop` -> `main`); include #1673 but not #1657 (test the latter on more machines before putting it on main)
- [x] Prepare release notes
- [x] Update wiki

**Comment by cz4rs** [comment]
Release created: https://github.com/DARMA-tasking/vt/releases/tag/1.1.1-beta.7
