### ISSUE TITLE
Build fails in the absence of libunwind

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#1691]
**Describe the bug**

On a system that doesn't have `libunwind` installed, building a project that incorporates vt leads to a compilation failure for missing `libunwind.h`

This will block integration of updated vt into EMPIRE.

https://github.com/DARMA-tasking/vt/pull/1657#issuecomment-1055754513

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by cz4rs** [comment]
DARMA weekly conclusion:
Preferred solution is to check for `libunwind` at CMake level, fallback to `libexecinfo` when not available and just print minimal information (only addresses?) when nothing is available.
