### ISSUE TITLE
Provide easier to digest LB statistic summary by default, output more detailed file

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1703]
**What Needs to be Done?**

We want to make statistics easier to digest for non-VT developers. Output more detailed file with statistics, with the option of disabling the file.

**Comment by PhilMiller** [comment]
Proposed output
> Ideal load balance would run in 27% less time

If applicable:
> Largest grain object limits load balancing improvement to 18% less time

**Comment by PhilMiller** [comment]
After LB:
> After load balancing, expected execution should take 15% less time
