### ISSUE TITLE
Create a test that checkpoints and restores a collection that has zero elements on some rank

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#1709]
There is at least one bug related to checkpointing and restoring a collection that has zero elements on some rank: https://github.com/DARMA-tasking/vt/issues/1708. We do not yet have a test for this.

**What Needs to be Done?**

- [ ] Create a collection and get it into a state where there is a rank with zero elements (either by setting it up that way initially or migrating everything off one rank)
- [ ] Checkpoint the collection
- [ ] Restore the collection and validate it

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by lifflander** [comment]
Here are some references for implementing this test. You can create a collection with a custom map function that excludes a particular node list this:

https://github.com/DARMA-tasking/vt/blob/e128b96d13c92c3c8b02c458a803c59eb0a39678/tests/unit/collectives/test_collectives_reduce.cc#L93-L116

With this in hand, you can add another test to this one that tests a collection that doesn't have elements on a particular node:

https://github.com/DARMA-tasking/vt/blob/develop/tests/unit/collection/test_checkpoint.extended.cc
