### ISSUE TITLE
Intel Classic compilers complaining about unsupported flag

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#1799]
**Describe the bug**
`icpc` 18 and 19 warn about unsupported command line option:
```
[490/634] Building CXX object tests/CMakeFiles/sequencer_nompi.dir/unit/main.cc.o
icpc: command line warning #10148: option '-ftemplate-backtrace-limit=100' not supported
```

**Additional context**
We already check this flag with `check_cxx_compiler_flag` before applying. Additional check for compiler type and version might be required.

**Comment by PhilMiller** [comment]
Huh, the documentation says that the check shouldn't accept the flag if there's any diagnostic

**Comment by cz4rs** [comment]
> Huh, the documentation says that the check shouldn't accept the flag if there's any diagnostic

Yeah, seems like a bug somewhere in between the CMake module and compiler. Works fine for me with CMake 3.18.4 and icpc 2021.6.
