### ISSUE TITLE
Port #1851 to a release

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#1871]
**What Needs to be Done?**

We need #1851 in a stable branch for EMPIRE users to not go crazy.

**Is your feature request related to a problem? Please describe.**

EMPIRE users are getting LB data files polluting their run directories

**Comment by PhilMiller** [comment]
Cezary, could you please take care of this and prepare a subsequent release?

**Comment by cz4rs** [comment]
Release created: https://github.com/DARMA-tasking/vt/releases/tag/1.1.1-beta.9.
