### ISSUE TITLE
migrate CI builds using `ubuntu-18.04` runner image to a newer version

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#1905]
**What Needs to be Done?**
The Ubuntu 18.04 Actions runner image is being deprecated (https://github.com/actions/runner-images/issues/6002). See the warning [here](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=39395&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3) for example.
Migrate all builds to a newer version.

**Comment by cz4rs** [comment]
Note to self: could this be enough?
```diff
--- a/scripts/workflows-azure.ini
+++ b/scripts/workflows-azure.ini
@@ -33,7 +33,7 @@ docker_target = "[% linux %]-cpp-clean"
 job_name = build
-workflow_runs_on = "vmImage: 'ubuntu-18.04'"
+workflow_runs_on = "vmImage: 'ubuntu-20.04'"
 build_root = $(ARCH)-[% linux %]-$(UBUNTU)-$(COMPILER)-cache
```

**Comment by PhilMiller** [comment]
If 22.04 is available, I think I'd prefer jumping as far forward as possible
