### ISSUE TITLE
Enable C++17 in some CI builds

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1906]
**What Needs to be Done?**
- [x] make it possible to select C++ standard version when building `vt`
- [x] make sure that C++14 remains the default
- [x] enable C++17 in at least one `clang` and one `gcc` build

**Comment by nmm0** [comment]
Related: https://github.com/DARMA-tasking/vt/issues/1974

**Comment by PhilMiller** [comment]
For the purpose stated, is there a reason we can't just configure with `-DCMAKE_CXX_STANDARD=17`?
