### ISSUE TITLE
Callback broadcast send to self even when message was send with deliver_to_sender=false

### ISSUE THREAD

**Issue by czajah** [DARMA-tasking/vt#2023]
This code works as expected sending message only to other nodes:

```
auto cb = ::vt::theCB()->makeBcast<CallbackMsg,callbackHandler>();
auto msg = vt::makeMessage<MyMsg>(cb,vt::theContext()->getNode());
vt::theMsg()->broadcastMsg<MyMsg, handler>(msg, false);
```

but in ```handler``` call to ```msg->cb_.send(vt::theContext()->getNode());``` send message also to the sender.

```
[ 0 ] Received message from 1
[ 1 ] Received message from 0
[ 1 ] callback from : 1
[ 0 ] callback from : 0
[ 0 ] callback from : 1
[ 1 ] callback from : 0
```

Is there an option to send callack without delivering to sender?

**Comment by PhilMiller** [comment]
To try to understand your request:

* Suppose the code is running on 2 nodes
```c++
if (vt::theContext()->getNode() == 0) {
  auto cb = ::vt::theCB()->makeBcast<CallbackMsg,callbackHandler>();
  cb.send(vt::theContext()->getNode());
}
```
* As vt currently operates, the handler will be called on both nodes, and print
```
[ 1 ] callback from : 0
[ 0 ] callback from : 0
```
* I think you're asking for something achieving the effect of
```c++
if (vt::theContext()->getNode() == 0) {
  auto cb = ::vt::theCB()->makeBcastExceptSelf<CallbackMsg,callbackHandler>();
  cb.send(vt::theContext()->getNode());
}
```
* Which would print
```
[ 1 ] callback from : 0
```

Is that correct? In particular, I'm trying to make sure that the message containing the callback isn't actually relevant to what you're looking for.

**Comment by PhilMiller** [comment]
Separately, at a higher level, I'm a bit nervous about the application design implied by a broadcast of a callback that itself will produce a broadcast. That entails P^2 uncoordinated messages, which is inherently non-scalable - it's both a performance concern, and likely to blow up message buffers at the level of MPI and below, leading to crashes.

**Comment by czajah** [comment]
@PhilMiller  I'm just plaing with vt trying to get to know it and I was looking for something like ```deliver_to_sender=false``` for ```theCB()->makeBcast``` I haven't found it so I thought that maybe if I send it in message by broadcast with ```deliver_to_sender=false``` it will magically inherit it. So, yes, I was looking for something like ```vt::theCB()->makeBcastExceptSelf``` and yes, probably you are right  that this is anyway not the best idea so I'm closing this issue. Thank you for reply!
