### ISSUE TITLE
Replace `detector` library with C++17

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#2046]
**What Needs to be Done?**
Replace, as much as possible, use of [detector](https://github.com/DARMA-tasking/detector) with C++17 constructs.

If it is possible to get rid of it completely, remember to remove it from build scripts, CMake and documentation, and archive the repository as well.

**Comment by nmm0** [comment]
Our plan now is to clean up the detector code, move it into Magistrate, and deprecate the detector library

**Comment by lifflander** [comment]
Actually, I'm going to take this since it's the only way to really fix the install problem in VT.
