### ISSUE TITLE
`Put compilation's and tests' logs in PR comment` CI step does not work

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#2054]
**What Needs to be Done?**
The message aggregating results from CI builds stopped showing up in PRs. The CI step gets executed and reports success, but there's an error showing up in [the output](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=45680&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=035f10b1-6721-511e-bd48-d7e028467fc2):

![image](https://user-images.githubusercontent.com/4639165/209866369-40734489-ec58-42f8-a808-5fb630461996.png)

**Comment by JacobDomagala** [comment]
Issue resolved with updated GitHub's PAT
