### ISSUE TITLE
Fix nvcc builds

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#2082]
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-4.0, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by PhilMiller** [comment]
Could you document in the issue description which nvcc build broken-ness is supposed to be addressed? 2 months later, I can't immediately reverse-engineer it from the PR substance.

**Comment by PhilMiller** [comment]
Also, if #2083 is superseded by #2103, please close the former in favor of the latter.
