### ISSUE TITLE
Fix `nvcc` missing return statement warnings

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#2111]
Follow-up to #2106.
`nvcc` raises bogus warnings when `if constexpr` is used. See [full logs](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=48388&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2) for details.
```
/vt/src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h(98)
```
https://github.com/DARMA-tasking/vt/blob/edf105def872ca2ec754e9d3e1ee9abed0c3039c/src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h#L80-L98

```
/vt/src/vt/objgroup/proxy/proxy_objgroup.impl.h(105)
```
https://github.com/DARMA-tasking/vt/blob/edf105def872ca2ec754e9d3e1ee9abed0c3039c/src/vt/objgroup/proxy/proxy_objgroup.impl.h#L87-L105

```
/vt/src/vt/vrt/collection/send/sendable.impl.h(156)
```
https://github.com/DARMA-tasking/vt/blob/edf105def872ca2ec754e9d3e1ee9abed0c3039c/src/vt/vrt/collection/send/sendable.impl.h#L133-L156

```
/vt/src/vt/vrt/collection/broadcast/broadcastable.impl.h(200)
```
https://github.com/DARMA-tasking/vt/blob/edf105def872ca2ec754e9d3e1ee9abed0c3039c/src/vt/vrt/collection/broadcast/broadcastable.impl.h#L180-L200

_Originally posted by @cz4rs in https://github.com/DARMA-tasking/vt/issues/2106#issuecomment-1473673354_

**Comment by JacobDomagala** [comment]
Note: This warning is fixed in nvcc 12 (actually it was reported to be fixed in 11.7)
