### ISSUE TITLE
sprintf warning on macOS

### ISSUE THREAD

**Issue by stmcgovern** [DARMA-tasking/vt#2125]
**What Needs to be Done?**

When building on mac I am seeing a warning of `'sprintf' is deprecated`
It recommends using `snprintf` .

Also might be useful to enable `-Werror` in macos builds.

**Comment by nlslatt** [comment]
Duplicate of https://github.com/DARMA-tasking/magistrate/issues/311

**Comment by nlslatt** [comment]
@thearusable There are two more uses of `sprintf` in vt that we need fixed. Thanks!
