### ISSUE TITLE
azure cuda 12.1 pipeline failures

### ISSUE THREAD

**Issue by stmcgovern** [DARMA-tasking/vt#2237]
The cuda 11.0 pipeline has not run since April 2023. https://dev.azure.com/DARMA-tasking/DARMA/_build?definitionId=12

In anticipation of application compiler stack upgrades, update it to cuda 12.1. Please adjust the pipeline pass/fail banners found on the vt homepage as appropriate.

This issue should not touch the cuda 11.2 pipeline. 

Edit: #2143 is related, but the pipeline does not run

**Comment by stmcgovern** [comment]
https://dev.azure.com/DARMA-tasking/DARMA/_build?definitionId=33
The cuda 12.1 pipeline has not yet completed successfully.

**Comment by JacobDomagala** [comment]
I'm able to reproduce it with 12.1, works fine for 12.2 and 12.3

**Comment by JacobDomagala** [comment]
@lifflander @stmcgovern Should we try to fix this error, or should we use 12.2 for our CI?

**Comment by stmcgovern** [comment]
Thanks for checking this @JacobDomagala ! Since there is no current need to use 12.1, I suggest we use 12.2 for the CI.  @lifflander what do you prefer?
