### ISSUE TITLE
Add stricter warnings for apps that use them

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#2264]
**What Needs to be Done?**

Add stricter warnings to cmake build

**Comment by cz4rs** [comment]
See https://github.com/DARMA-tasking/magistrate/issues/333 for a similar issue in magistrate.

**Comment by cz4rs** [comment]
TODO: also consider fixing [codacy issues](https://app.codacy.com/gh/DARMA-tasking/vt/issues/current), there are some interesting ones listed.
