### ISSUE TITLE
Update CI to use Docker Compose V2 on Azure

### ISSUE THREAD

**Issue by thearusable** [DARMA-tasking/vt#2312]
Warning to be fixed:
The task is utilizing Docker Compose V1, but there are plans to transition to Docker Compose V2. It's necessary to investigate how to adapt your project to Docker Compose V2. For guidance on this migration, you can refer to the official Docker Compose documentation at the provided link: https://docs.docker.com/compose/migrate/

**Comment by cz4rs** [comment]
We could fix some GitHub actions warnings as well:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20
```

**Comment by cz4rs** [comment]
Regarding Docker Compose v2:
https://github.com/DARMA-tasking/vt/pull/2315/commits/81869c653380a5c808f6d90b04bc51448b01b35a can be used as a workaround for `invalid project name` error. The only other warning I've seen so far is `level=warning msg="/home/vsts/work/1/s/docker-compose.yml: ``version`` is obsolete`.
