### ISSUE TITLE
Build Spack package job cannot find magistrate.

### ISSUE THREAD

**Issue by thearusable** [DARMA-tasking/vt#2325]
CI output:
https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=59455&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=28db5144-7e5d-5c90-2820-8676d630d9d2

**Comment by JacobDomagala** [comment]
https://github.com/DARMA-tasking/spack-package/issues/19

There's already an issue for that

**Comment by thearusable** [comment]
Ah ok, I missed that issue.
