### ISSUE TITLE
Replace is_same<..., Footprinter> with is_footprinter<...>

### ISSUE THREAD

**Issue by Matthew-Whitlock** [DARMA-tasking/vt#2354]
Once Magistrate merges in https://github.com/DARMA-tasking/magistrate/pull/345, the type passed to serializers will be a wrapper around the old serializer types. This requires changing one line in VT:

https://github.com/DARMA-tasking/vt/blob/5538883df647dc7ed93f19f751d425a5d03b24a0/src/vt/messaging/message/smart_ptr.h#L239

Which can become:
`
    checkpoint::is_footprinter_v<SerializerT>
`

**Comment by PhilMiller** [comment]
The standard suggestion for not breaking CI and other work flows is to introduce that tiny type trait in a preliminary PR that can be merged easily and make the necessary change in vt before anything will break without it. It looks like it would be pretty trivial to separate the non-specialized bits in https://github.com/DARMA-tasking/magistrate/pull/345/files#diff-55e1997dc89d4418466fb76518870de26637ba41f902ddb390280457c69724b9 in magistrate
