### ISSUE TITLE
Flush traces every X steps

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#241]

**Comment by uhetmaniuk** [comment]
- Add a parameter to control how often flushing occurs
- Create a routine "flush" that could be call from load balancer and/or third-party software

Note: When one thread needs to flush, all the threads should flush at the same time. It is important to synchronize the flushing actions.

**Comment by uhetmaniuk** [comment]
@lifflander : we discussed on Tuesday to place the flush before/after calling the load balancing (i.e. when all the threads are synchronized). Can I assume that the "synchronization" would be done outside the flushing routine?

**Comment by lifflander** [comment]
Can you make a synchronized (barrier at start) *and* non-synchronized call that flushes the trace? Then, we can add the non-synchronized call into the LBManager, after LB's synchronization occurs already. We should add an argument for turning on LB phase flushing (off by default).

**Comment by uhetmaniuk** [comment]
@lifflander By flushing, do you mean: 
- just `writeTracesToFile`,
- `writeTracesToFile` + *something else*? 
When we discussed the sizes (in MB), do we mean the *relative* length of the vector `traces_` since the latest flush?

**Comment by lifflander** [comment]
If you can figure out a way to calculate approximately the number of bytes per log entry, we can convert the length of that vector into a dump frequency if the user specifies based on size (MB).

Flushing will be similar to `writeTracesToFile`, but ensure that it only dumps at coherent points and closes the file descriptor and re-opens it so if the program crashes it will be written to disk.

**Comment by lifflander** [comment]
Merged, closing
