### ISSUE TITLE
ensure collections are propagated before inserting

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#273]
I may have run into a possible issue with insertable collections. When inserting I would (typically with 8 or more cores on my local machine) get an abort stating that the collection I am inserting to doesn't exist.

I think the collection creation hasn't propagated before insert is called.

I fixed this in my code by calling `::vt::theCollective->barrier()` after creating the insertable collection, but that's a temporary solution.

I will work on getting a reproducible test case.

**Comment by lifflander** [comment]
We believe this is fixed now, but we don't know for sure.
