### ISSUE TITLE
Automatically synthesize message types for sends to arbitrary handlers

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#276]
Following on #272, I think it would not be all that difficult to write template code that would let applications make a `send` call with arguments matching those of some handler, and the template code would take care of describing a suitable message type and actual target handler to unwrap the message and make the call.

The pieces I see playing into this are roughly as follows:

* A method (probably easy enough to write with [`std::forward_as_tuple`](https://en.cppreference.com/w/cpp/utility/tuple/forward_as_tuple)
`template <void (*Func)(Args...), typename Args...> sendMagic(Args&& ...args)`
* A very generic message type 
`template <typename Args...> struct MagicMsg { std::tuple<...Args> a;};`
* A very generic handler function to call the actual handler via [`std::apply`](https://en.cppreference.com/w/cpp/utility/apply)
`template <void (*Func)(Args...), typename Args...> receiveMagic(MagicMsg<...Args>* m)`

Once the simplest cases are working, we should probably apply a type trait to each of the argument types to represent how they should be represented in the message / on the wire, in cases where they shouldn't be literal. In particular, automatic handling of anything array-like on the sending side coming out to whatever array-like thing the receiver expects would be very convenient.

**Comment by PhilMiller** [comment]
More than a year later, Nvidia is still the laggard in implementing P0127 support. I'm going to de-assign this, just to take it off the radar.

**Comment by lifflander** [comment]
@PhilMiller Sounds like a plan. Should be have a label for back burner type tasks? Is pri:low enough to signify that?

**Comment by PhilMiller** [comment]
Yeah, I think so.

**Comment by PhilMiller** [comment]
And, as a note, Nvidia's compiler generally says that it doesn't implement partial standards, so we won't have any C++17 support from them until they offer complete C++17 support. We should maybe see if this code would work there in spite of their lacking support, possibly by it not parsing code that it's not going to need to generate anything for itself.

**Comment by PhilMiller** [comment]
As of nvcc 11.0, C++17 support is available.
