### ISSUE TITLE
tests fail in trace builds

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#342]
I generally get two tests failing on both debug and release on my local machine. However I get 88 tests failing on release_trace.
[debug.log](https://github.com/darma-mpi-backend/vt/files/3044866/debug.log)
[release.log](https://github.com/darma-mpi-backend/vt/files/3044868/release.log)
[trace.log](https://github.com/darma-mpi-backend/vt/files/3044874/trace.log)

This is with gcc 8.1 and mpich 3.2.1

**Comment by lifflander** [comment]
This is fixed, closing
