### ISSUE TITLE
Routine to run function/action/lambda in suspendable thread

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#413]
For the expedient sake of blocking reductions as currently used in EMPIRE, it would be really useful if a handler could call some function like

`void runInThread(std::function<void()> F)`

That would create a context thread and call the function `F` within it. We need ancillary routines to
* get a reference to the running thread
* suspend the running thread (error if it wasn't one created as above)
* resume a thread

In the blocking reduction use case, the VT handler would call the above routine, passing an argument of the current code that calls reductions. The reduction implementation would add an action to resume the current thread when the reduction completes, submit its contribution, and then suspend.

**Comment by PhilMiller** [comment]
Live threads need to be tracked by termination detection, producing at initiation and consuming at completion.

**Comment by PhilMiller** [comment]
We may want to arrange vt to run all handlers in threads, and just do some caching/pooling to avoid excessive overhead from repeated (de)allocation

**Comment by PhilMiller** [comment]
The new use case that brings attention back to this issue is the desire to tie a handler's execution to a CUDA stream, with the ability to fence mid-handler, keeping its epoch unterminated, without actually blocking all of execution.

**Comment by lifflander** [comment]
Ok, let's revive this issue

**Comment by PhilMiller** [comment]
Jonathan says scheduler calls in threads should always `yield()` to the scheduler thread

He also says suspended threads should put TD for the associated epoch on hold, so they don't spin trying to make progress.

**Comment by PhilMiller** [comment]
@nmm0 is also potentially interested in using this capability

**Comment by nmm0** [comment]
Some contact use-cases have handlers that are blocking communication, would be useful to be able to suspend the handler and see how it affects performance
