### ISSUE TITLE
Debugging feature: in-process 'migration'

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#430]
I'd like to be able to debug serialization logic in a single process. This could be facilitated by a setting in which calls for 'load balancing' result in every object being packed and unpacked within the same process. This would miss some issues with references to global/static variables or other process-level state, perhaps, but would make it a lot easier to work on object-level state.

**Comment by lifflander** [comment]
Closing this as it is the same as https://github.com/DARMA-tasking/vt/issues/476
