### ISSUE TITLE
Read in VT object file and migrate objects accordingly

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#431]
Currently, VT can only write an object map file. See `ProcStats::outputStatsFile` in `src/vt/vrt/collection/balance/proc_stats.cc` for the implementation of writing out the map. We need to read in the map (without communication edges) and then migrate objects based on that mapping. A new load balancer may need to be created to do this.

**Comment by lifflander** [comment]
More detailed commends based on our discussion:

The system currently sets `proc_data_` for each phase as the program runs. `proc_data_` contains instrumentation which is valuable to the runtime even when following a user-specified map. It's the data structure that has how long each object takes, which should not be modified with `proc_data_`

We do need a new data structure for a user-specified map. It can go in `ProcStats`, but we could call it something else, maybe `user_specified_map`.

After the map is populated, the data from the map needs to be imported into the LB. Instead of messing with `startLBHandler`, we should just read it in `runLB` in the new load balancer. `BaseLB::phase_` will tell you which phase you are on so you can index the first dimension of the `user_specified_map`. 

Next, after reading, we should do reductions to determine if any object has moved for a given phase. Each processor can do this by locally checking if the `user_specified_map[i]` is different than `user_specified_map[i+1]`. We can create a `std::vector<bool>` locally and then boolean or reduce that vector across the whole machine into a new variable `std::vector<bool> user_specified_map_changed;`. Then, in `LBManager::decideLBToRun`, if the load balancer is from a file user-specified, we should index that vector to determine if it needs to run.

The remainder is just calling `migrateObjectTo(ProcStats::proc_perm_to_temp_[obj_id], this_node)`

**Comment by mperrinel** [comment]
Thank @lifflander for the details !

So I updated the _proc_data__ stats to keep its old behaviour. In addition the _user_specified_map__ variable member store the data coming from the input file.
In the new _StatsMapLB_ class, I added a new variable of type _std::vector<bool>_ that is filled using the difference between the _user_specified_map_[I+1]_ and the _user_specified_map_[I]_. the size of this vector is _user_specified_map.size() - 1_. If there is at least one difference between the two phases, then the correspondant vector value is set to true. By doing that, I don't really have a boolean value for every load of a phase but a unique boolean value for all the Loads.
I didn't find the _LBManager::decideLBToRun_ method but in the _runLB_ method, I do the migration for a phase only if the correspondant _std::vector<bool>_ is _true_.
I need more information about std::vector<bool> reduction.
Let's talk about that at the meeting.

**Comment by lifflander** [comment]
@mperrinel Here's a snippet of how you might do a reduce:

```C++
namespace vt { namespace collective { namespace reduce { namespace operators {

template <typename T>
struct OrOp<std::vector<T>> {
  void operator()(std::vector<T>& v1, std::vector<T> const& v2) {
    vtAssert(v1.size() == v2.size(), "Sizes of vectors in reduce must be equal");
    for (size_t ii = 0; ii < v1.size(); ++ii)
      v1[ii] = v1[ii] or v2[ii];
  }
};

}}}} /* end namespace vt::collective::reduce::operators */


struct StatsMapLB {
  using ReduceMsgType = collective::ReduceVecMsg<bool>;
  void doneReduce(ReduceMsgType* msg) {

  }

  void doReduce() {
    auto cb = theCB()->makeBcast<StatsMapLB,ReduceMsgType,&LBManager::doneReduce>(proxy);
    auto msg = makeMessage<MsgType>(in_vector);
    proxy.reduce<OrOp<std::vector<int>>>(msg.get(),cb);
  }

private:
  objgroup::proxy::Proxy<RotateLB> proxy = {};
};
```

This might not compile, but that's an example of what you need to write.

**Comment by mperrinel** [comment]
I rebased the feature to develop. Now I try to understand the the LBmanager and the objGroup and how I can use it correctly to do the reduction. I'll do an update later.

**Comment by lifflander** [comment]
Cool, sounds good. Basically create a new objgroup for reading and processing the input files. Should be created by the Runtime at startup (late in the process). Use a static init/destroy as in LBManager to instantiate it collectively. Once you have an objgroup, you can use the proxy to reduce or send messages to coordinate when to dispatch to StatsMapLB

**Comment by mperrinel** [comment]
I have created a new class StatsLBReader that aims to 

- Read the input stat file (_inputStatsFile_ method)
- Do the local difference between phases into a vector<bool> (loadPhaseChangedMap method)
- Call the doReduce method.
- Is initialised from the _Runtime::initialize_ method : `vrt::collection::balance::StatsLBReader::init();`

The _init_ method of the StatsLBReader does : 
```
  StatsLBReader::proxy_ = theObjGroup()->makeCollective<StatsLBReader>();
  proxy_.get()->inputStatsFile();
  proxy_.get()->loadPhaseChangedMap();
```

I put the doneReduce method on the LBManager struct  but `the auto cb = theCB()->makeBcast<lb::StatsMapLB,ReduceMsgType,&balance::LBManager::doneReduce>(this->getProxy());` implemented into the doReduce method still doesn't compile.

I'm working on it...

**Comment by mperrinel** [comment]
I moved the doneReduce method from the _LBManager_ to the _StatsLBReader_ and the instruction `auto cb = theCB()->makeBcast<StatsLBReader,ReduceMsgType, &StatsLBReader::doneReduce>(this->getProxy());` now compiles.

This is the current doReduce implantation : 
 ```
 auto cb = theCB()->makeBcast<StatsLBReader,ReduceMsgType, &StatsLBReader::doneReduce>(this->getProxy());
    auto msg = makeMessage<ReduceMsgType>(StatsLBReader::phase_changed_map_);
    this->getProxy().reduce<collective::OrOp<std::vector<bool>>>(msg.get(),cb);
```

The last instruction doesn't compile : 
```
/Users/perrinel/Dev/vt-auto-build/build-vt-all-gcc/vt/vt/src/vt/vrt/collection/balance/stats_lb_reader.cc:212:22: note: in instantiation of function template specialization 'vt::objgroup::proxy::Proxy<vt::vrt::collection::balance::StatsLBReader>::reduce<vt::collective::reduce::operators::OrOp<std::__1::vector<bool, std::__1::allocator<bool> > >, vt::collective::reduce::operators::ReduceVecMsg<bool> *, vt::collective::reduce::operators::ReduceVecMsg<bool>, &vt::collective::reduce::operators::ReduceCombine<void>::msgHandler>' requested here
    this->getProxy().reduce<collective::OrOp<std::vector<bool>>>(msg.get(),cb);
                     ^
/Users/perrinel/Dev/vt-auto-build/build-vt-all-gcc/checkpoint/checkpoint-install/include/dispatch/dispatch.impl.h:153:13: note: candidate template ignored: could not match 'T *' against '__bit_iterator<std::__1::vector<bool, std::__1::allocator<bool> >, false>'
inline void serializeArray(Serializer& s, T* array, SerialSizeType const num_elms) {
```

Does the serialiser is _vector<bool>_ compatible ?

**Comment by mperrinel** [comment]
I think `this->getProxy().reduce<collective::OrOp<std::vector<bool>>>(msg.get(),cb);` is not correct because msg.get() is of type _ReduceMsgType_ which is not the same type of _std::vector<bool>_.

I can also see something that is similar to what I want to do in _test_objgroup.cc_ file (l 262) : `proxy4.reduce<PlusOp<VectorPayload>, Verify<4>>(msg4);`

Maybe I have to put my vector<bool> into a new struct ? and do something that is similar to the _VectorPayload_ defined in the test_obj_group_common.h

**Comment by mperrinel** [comment]
@lifflander the branch 431-vt-object-file-reader-2 contains the latest version.

**Comment by lifflander** [comment]
The problem is that `std::vector<bool>` has special semantics. A general serializer, as written in checkpoint, can't be used to serialize that vector because you can't take a reference to a single element (i.e., bit iterator `__bit_iterator`). Read this article: [Vector of Bool](https://isocpp.org/blog/2012/11/on-vectorbool)

We need to write an overload for vector of bool in checkpoint. I'm creating an issue for that and assigning it to you.

**Comment by mperrinel** [comment]
ok thanks for the link.

**Comment by mperrinel** [comment]
@lifflander 

On the `Runtime::initialize` method, I call the `vrt::collection::balance::StatsLBReader::init();`
This method is called one per node. 
```
/*static*/ void StatsLBReader::init() {
  // Create the new class dedicated to the input reader
  StatsLBReader::proxy_ = theObjGroup()->makeCollective<StatsLBReader>();
  proxy_.get()->inputStatsFile();
  proxy_.get()->loadPhaseChangedMap();
  proxy_.get()->doReduce();
}
```
Its implementation consists on 

1. Creating the StatLBReader class using theObjGroup()->makeCollective method
2. Calling the inpustStatsFIle() of the StatLBReader instance that reads for each node the correspondant input stat file.
3. Calling the loadPhaseChangedMap() of the StatLBReader instance that computes the phase (vector of bool of size : (numberOfPhase - 1))
4. Calling the doReduce() method of the StatLBReader instance that do the reduction.

I need now to understand how works the reductions : 
```
 using ReduceMsgType = collective::ReduceVecMsg<bool>;

 auto cb = theCB()->makeBcast<StatsLBReader,ReduceMsgType, &StatsLBReader::doneReduce>(this->getProxy());
 auto msg = makeMessage<ReduceMsgType>(this->getProxy().get()->phase_changed_map_);
 this->getProxy().reduce<collective::OrOp<std::vector<bool>>>(msg.get(),cb);
```
This implementation of the reduction aims to create a msg and broadcasts it. 
I imagine the reduction done by the proxy with the OrOp operator should combine all vectors of bool already filled by the loadPhaseChangedMap() method for each node in one another and unique vector that will later be used to check if for a specific phase , the LB should be run.
1. Why the doneReduce method isn't call ?
2. Where the unique and global vector<bool> should be declared ?

**Comment by mperrinel** [comment]
Currently the feature crashes and that is the output :

```
iteration: iter=7,time=0.12256400000000012
vt: [0] lb: LBManaager::releaseNow: finished LB, phase=7, invocations=0
vt: [3] lb: outputStatsFile: file=0x7fffb2508030, iter=8
vt: [1] lb: outputStatsFile: file=0x7fffb2508030, iter=8
vt: [2] lb: outputStatsFile: file=0x7fffb2508030, iter=8
vt: [0] lb: outputStatsFile: file=0x7fffb2508030, iter=8
vt: Total work units processed: 1799
vt: Runtime Finalizing
vt: Caught SIGSEGV signal: 11 
vt: Caught SIGSEGV signal: 11 
0    18   0x10fd70ce0     vt::debug::stack::dumpStack(int) + 64
1    18   0x10fd72c70     vt::runtime::Runtime::sigHandler(int) + 288
2    18   0x7fff7f6efb5d  _sigtramp + 29
         3 18 0x0 3   ???                                 0x0000000000000000 0x0 + 0
4    18   0x10fcf05e3     std::__1::__vector_base<vt::messaging::MsgSharedPtr<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::allocator<vt::messaging::MsgSharedPtr<vt::collective::reduce::operators::ReduceVecMsg<bool> > > >::~__vector_base() + 83
5    18   0x10fce988c     std::__1::unordered_map<unsigned long long, std::__1::unordered_map<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long>, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::hash<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::equal_to<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::allocator<0    18   0x101ebcce0     vt::debug::stack::dumpStack(int) + 64
1    18   0x101ebec70     vt::runtime::Runtime::sigHandler(int) + 288
2    18   0x7fff7f6efb5d  _sigtramp + 29
         3 18 0x0 3   ???                                 0x0000000000000000 0x0 + 0
4    18   0x101e3c5e3     std::__1::__vector_base<vt::messaging::MsgSharedPtr<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::allocator<vt::messaging::MsgSharedPtr<vt::collective::reduce::operators::ReduceVecMsg<bool> > > >::~__vector_base() + 83
5    18   0x101e3588c     std::__1::unordered_map<unsigned long long, std::__1::unordered_map<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long>, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::hash<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::equal_to<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::allocator<std::__1::pair<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> const, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> > > > >, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::unordered_map<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long>, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::hash<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::equal_to<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::allocator<std::__1::pair<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> const, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> > > > > > > >::~unordered_map() + 60
6    18   0x7fff7f5b03cf  __cxa_fistd::__1::pair<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> const, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> > > > >, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<unsigned long long const, std::__1::unordered_map<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long>, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> >, std::__1::hash<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::equal_to<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> >, std::__1::allocator<std::__1::pair<std::__1::tuple<int, unsigned long long, unsigned long long, unsigned long long> const, vt::collective::reduce::ReduceState<vt::collective::reduce::operators::ReduceVecMsg<bool> > > > > > > >::~unordered_map() + 60
6    18   0x7fff7f5b03cf  __cxa_finalize_ranges + 319
7    18   0x7fff7f5b06b3  exit + 55
8    18   0x7fff7f50a3dc  start + 8


nalize_ranges + 319
7    18   0x7fff7f5b06b3  exit + 55
8    18   0x7fff7f50a3dc  start + 8
```

If we comment 
`this->getProxy().reduce<collective::OrOp<std::vector<bool>>>(msg.get(),cb);`

There is no crash anymore but also no reduction too.
I'm not sure that it's possible to reduce the msg with a static vector.

@lifflander, ifyou can branch on the feature and test it that could be very useful for me.

**Comment by mperrinel** [comment]
I found a way to make call the doneMethod correctly using a solution similar to what have been done on the `test_objgroup_common.h` and its `VecMsg` and `VectorPayload` structs.

Basically, the vector of bool is not directly the one on which we are trying to do the reduction but it is encapsulated as an attribute inside a VectorDiffPhase new struct on which the `Operator || `and a serializer have been added. If this fix is ok we can implement the doneReduce method.

**Comment by lifflander** [comment]
```C++
template <typename T>
struct ReduceVecMsg : ReduceDataMsg<std::vector<T>> {
  using DataType = std::vector<T>;

  ReduceVecMsg() = default;
  explicit ReduceVecMsg(DataType&& in_val)
    : ReduceDataMsg<DataType>(std::forward<DataType>(in_val))
  { }
  explicit ReduceVecMsg(DataType const& in_val)
    : ReduceDataMsg<DataType>(in_val)
  { }

  template <typename SerializerT>
  void serialize(SerializerT& s) {
    ReduceDataMsg<std::vector<T>>::invokeSerialize(s);
  }
};

````

**Comment by uhetmaniuk** [comment]
@lifflander 
How should I interpret the map specified in the input file?
- Is it a map for a restart (meaning that I use the input data once before restarting the simulation)?
- Or a specific map for every iteration? (in that case, do I abort the code if there are more iterations in the simulation than iteration data in the input file?)

**Comment by uhetmaniuk** [comment]
@lifflander 
Do I understand correctly that, if I output stats from one simulation "lb_iter.exe" with GreedyLB, then reading these files in a subsequent simulation would give me the same simulation (as the first one)?

**Comment by lifflander** [comment]
@uhetmaniuk Yes, it should give the same object distribution each iteration.

**Comment by lifflander** [comment]
The number of iterations should match, but you could take the min/just ignore iterations past the file specification.

**Comment by lifflander** [comment]
The map is for a restart

**Comment by uhetmaniuk** [comment]
@lifflander I believe to understand the difference between `tempID` and `permID`. I have prepared the migration of elements at the end of an iteration.
It looks like my changes do not propagate to the variable `balance::ProcStats::proc_data_` (i.e. the inserted elements at the new phase are the old _non-migrated_ elements).
Do you recall which step / function link the migration to the insertion of elements in `balance::ProcStats::proc_data_` ?

**Comment by uhetmaniuk** [comment]
@lifflander @ppebay 
My understanding is that baseLB::migrateObjectTo expects a temp_id as first parameter before migrating an element.
At iteration $i$, I know:
- the pair (temp_id, perm_id) for the elements currently on a node
- the list of perm_id for the elements on a node for the next iteration
I am afraid that I am missing a piece of information for the migration of elements across nodes: like where do they come from? or where are they going?
Could you comment on this aspect?
