### ISSUE TITLE
Bug in DS termination occasional failure

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#439]
```bash
mpirun -n 8 ./tests/test_term_dep_send_chain --gtest_filter="*/TestTermDepSendChain.test_term_dep_send_chain/DStrueK3MIGRATEfalse"
```

In fish, I use this to reproduce and must run something along side it to perturb it.

```fish
while test $status -eq 0; echo run; mpirun -n 8 ./tests/test_term_dep_send_chain --gtest_filter="*/TestTermDepSendChain.test_term_dep_send_chain/DStrueK3MIGRATEfalse" > out ;end
```

**Comment by PhilMiller** [comment]
@nlslatt Is it possible this is the failure you're seeing, just made more frequent/apparent by your change?

**Comment by nlslatt** [comment]
Thank you, @PhilMiller.  I was looking for this issue but the search failed me.  This particular test case (using just the first command in the issue description) is passing for me.

**Comment by PhilMiller** [comment]
If the tests are structured similarly, timing shifts could shuffle up which ones pass or fail

**Comment by lifflander** [comment]
Merged, closing after a lot of testing
