### ISSUE TITLE
Split stage runtime initialization and argument resolution

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#444]
Split runtime init into two phases. Resolve argument conflicts with clear precedence.

**Comment by lifflander** [comment]
@uhetmaniuk I think I agree with Nicole. I think we should parse the YAML in EMPIRE and then pass the `ArgConfig` object to VT. I want to the user to be able to supply multiple configurations at different levels in the code that get resolved. 

A couple minor additions:
- I want to adding an option in VT to dump the final configuration file (CLI11 does bidirectional config file input and output) using a opt-in argument. Maybe `--vt_dump_config`.
- We should add an option for specifying a config file as CLI11 can take that directly (it supports ini files without any extra work!).  https://github.com/CLIUtils/CLI11#configuration-file

**Comment by lifflander** [comment]
I would also like you to write some general code that handles printing configuration at startup (`vt::Runtime::printStartupBanner`). Right now, there's a lot of specialized code for that that is error prone. This will also help with correctly/automatically outputting precedence resolution decisions.

I'm thinking:

```C++
struct ArgumentBase {
  virtual void addToAppParse() = 0;
};

template <typename T>
struct Argument : ArgumentBase {

  void addToAppParse() override {

  }

  static constexpr bool isFlag() { return std::is_same<T,bool>::value; }

  std::string arg_;
  std::string desc_;
  T value = {};
  T default = {};
  std::function<std::string(T const& value)> print_value = nullptr;
  std::function<bool(T const& value) print_condition = nullptr;
  bool always_print_startup_;
};



```

**Comment by uhetmaniuk** [comment]
@lifflander I would like to clarify a few questions:
- why do we update argc and argv after parsing them? (I could not find a place where the updated values are needed);
- do you envision "resolveOptions" to be called after calling the CLI parser?
- the Config object will combine, for each parameter, the default value (possibly updated by EMPIRE), the command-line value, and the input file (YAML) value. CLI will only be aware of the command-line value and the default value. The output from CLI will not see the input file (YAML) commands. Am I missing something?

**Comment by lifflander** [comment]
- We must update argc/argv because they get passed to EMPIRE after VT uses them. If the options are not removed, EMPIRE will see unexpected arguments.

- Yes, `resolveOptions` will be called during `Runtime::initialize`, in the new split design, after the allocation and various overloads are added.

- We are not using CLI to parse the YAML. CLI only handles the command-line flags. The new value/default overloads will specify the value directly, and just match the command name for the flag (which can be different than the command-line argument name).

**Comment by uhetmaniuk** [comment]
@lifflander OK.
For the last point, I was discussing the possibility of writing out to a ".ini" file the configuration used (so using CLI to write the ".ini" file -- as we discussed).

**Comment by lifflander** [comment]
Oh, I mis-read what you were saying. Yes, I think you are right. So maybe it won't be as useful in the context of EMPIRE (or other users that overload).

**Comment by uhetmaniuk** [comment]
This issue is handled in the "cleaned" [branch](https://github.com/DARMA-tasking/vt/tree/444-split-runtime-init-cleaner)

**Comment by lifflander** [comment]
Closing this issue as the methodology for making this more flexible is far too complicated for the benefit it provides. Instead, we propose a simpler methodology that the user just pass an `AppConfig` if they want to configure things programmatically. See new issue: https://github.com/DARMA-tasking/vt/issues/1550
