### ISSUE TITLE
Ordering error in command-line arguments

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#450]
The vt command-line arguments are being processed in the wrong (reverse?) order.  Examples:

This creates a directory called `--vt-trace` and uses it as the tracing directory:
```
mpirun -np 2 ./hello_world --vt_trace --vt_trace_dir tracing_directory
```

This tries to create a directory called `./hello_world`:
```
mpirun -np 2 ./hello_world --vt_trace_dir tracing_directory --vt_trace
```

This creates the tracing directory `tracing_directory`:
```
mpirun -np 2 ./hello_world tracing_directory --vt_trace_dir --vt_trace
```

@lifflander @uhetmaniuk @PhilMiller

**Comment by lifflander** [comment]
This is odd, looking into it.

**Comment by lifflander** [comment]
@nlslatt I'm investigating this more, something very strange is going on. Also, order should **never** matter on the arguments.

**Comment by lifflander** [comment]
It works with the `=` not a space. Reversing seems like it could be the culprit, but they shouldn't be reversed when passing to CLI11.

```
./examples/hello_world  --vt_trace --vt_trace_dir=test123  --vt_trace_file=xxx --vt_trace_mod=10
./examples/hello_world  --vt_trace --vt_trace_dir test123  --vt_trace_file xxx --vt_trace_mod 10
```

**Comment by lifflander** [comment]
Found the bug, CLI11 is reversing it by default when you call with a `std::vector<std::string>`

**Comment by lifflander** [comment]
Merged, closing
