### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by mperrinel** [DARMA-tasking/vt#477]
**What Needs to be Done?**
- [ ] Choose the appropriate CI solution
- [ ] Setup the chosen one

**Is your feature request related to a problem? Please describe.**
A jenkins had been setup previously on a local machine, connected to a fake VT project and was able to do all required [feature](https://github.com/DARMA-tasking/vt/issues/299):
- Scan and run a build when a new commit or a new pull request shows up on Github. Ideally, the model will be "push-based": Github informs Jenkins of a change that requires a new build.
- Mark the Github commit with a success or failure symbol corresponding of the Jenkins build results itself. Direct link from Github to Jenkins to dive into the results of the build.
- Make the Jenkins GitHub User a required reviewer for each Pull request. Automatically reject a pull request on the basis of Jenkins testing.
- Review the pull request with a comment and a status of validation corresponding of the Jenkins build results itself.

The problem is now to deploy the local Jenkins into a Sandia server.

**Describe potential solution outcome**
Install the missing plugins on the Sandia Jenkins server :

What we need : 
- workflow-job@2.32
- pipeline-model-definition@1.3.6
- workflow-multibranch@2.21
- branch-api@2.0.21
- github-branch-source@2.4.2
- git@3.9.3
- scm-api@2.3.0

What it's already there : 
- workflow-job  - Now part of Pipeline plugin, called Pipeline: Job Plugin v 2.3.1
- pipeline-model-definition  - Now part of Pipeline plugin, called Pipeline: Declarative,  v. 1.3.6
- workflow-multibranch  - Now part of Pipeline plugin, called Pipeline: Multibranch , v. 2.21
- branch-api , v. 2.1.2
- git, v. 1.294
- scm-api, v. 2.3.0

What is missing : 

- github-branch-source (v. 2.4.5 available)

What need to be verified:
We need to verify if commun plugins have the same behaviour despite their different version.

**Describe alternatives you've considered**
1) Create the Jenkins into a new server to : 
- Install every plugins that we need
- Get the Jenkins be faster since it is dedicated to VT
2) Think about CI alternative (gitlab-ci, circle-ci) in their public version, with the possibility to paid features if the company is US based. 

**Additional context**

**Comment by pnstickne** [comment]
@lifflander Can close issues given CI on GitHub?

**Comment by lifflander** [comment]
Yes, let's close this. We have all the CI setup that we need now through GitHub.
