### ISSUE TITLE
Array overrun when argument parsing

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#482]
**Describe the bug**
args.cpp:473
```cpp
int new_argc = ret_args.size() + 1;
  char** new_argv = new char*[new_argc + 1];
  new_argv[0] = argv[0];
  for (auto ii = 1; ii < new_argc; ii++) {
    new_argv[ii] = argv[ret_idx[ii]];
  }
```

ret_idx and ret_args have the same size which is one less than new_argc. Therefore if there are application arguments (new_argc > 1) ret_idx will be accessed at index ret_idx.size() and segfault

**To Reproduce**
1. Example/test/snippet of code that fails

Fails on VT launch

2. Compiler, platform, libraries

Any

3. Run command: number of processors, threading options, etc.

Run a VT application with application-specific parameters, e.g. catch2 tests:
```sh
tests/BVHTests -r xml -d yes --order lex
```

**Expected behavior**
Arguments sent back to user code

**Screenshots**

**Platform (please complete the following information):**
 - Linux desktops
 - gcc 9.2
 - mpich2
 - develop

**Additional context**

**Comment by lifflander** [comment]
Merged
