### ISSUE TITLE
Reduce global cost of CLI11 ("CLI11.hpp" inclusion)

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#489]
Currently CLI11.hpp is include via 'args.h'; this causes needless slowdown of every individual TU pulling in such as a dependency by at least ~2 seconds (very conservatively, probably closer to 4 locally).

- CLI11.hpp should be abstract / extracted from all primary header inclusion behind it's own TU for compilation and access.

<img width="772" alt="CLI11-per-include-overhead" src="https://user-images.githubusercontent.com/1430176/66286032-54f23f80-e884-11e9-8bc3-4d9badaacfb2.png">

**Comment by lifflander** [comment]
Created a new branch `489-remove-global-cli11-include` to implement this fix

**Comment by pnstickne** [comment]
Changed merged into origin/develop - here is event_id.cc.json again building with the changes locally.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1430176/66366357-022c8c80-e945-11e9-92ec-49710ca6bd93.png">

From ~10s to ~2.5s.

**Comment by pnstickne** [comment]
Still other improvements to maybe remove another second or so. Should work to favor forward declares when such are unified.
