### ISSUE TITLE
Make clang-format keep nested namespaces on one line

### ISSUE THREAD

**Issue by uhetmaniuk** [DARMA-tasking/vt#498]
**What Needs to be Done?**

- [x] Add command "CompactNamespaces: true"

**Is your feature request related to a problem? Please describe.**
clang-format breaks the nested namespaces into multiple lines.
The behavior is not consistent with the coding guidelines.

**Describe potential solution outcome**
- Add command "CompactNamespaces: true"

**Comment by lifflander** [comment]
Merged, closing
