### ISSUE TITLE
Implement non-heuristic-based termination hang detection 

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#500]
**What Needs to be Done?**

- [ ] Add check for queues empty (might want to build off of #474)
- [ ] When many traverses reveal the same counter, do a reduction to check for empty queues also.
- [ ] Reveal the live epochs related to the hang

**Is your feature request related to a problem? Please describe.**

We recently had a problem where the current hang detection, which is a heuristic, caused us to believe a bug existed that didn't on a very slow over-subscribed machine.

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by nlslatt** [comment]
I've now seen this without oversubscribing (4 ranks on 4 physical nodes).

**Comment by lifflander** [comment]
I'm implementing a variant of this algorithm: [_Distributed Deadlock Detection_ by Chandy and Misra](http://lass.cs.umass.edu/~shenoy/courses/677/readings/Chandy_dist_deadlock.pdf)

**Comment by lifflander** [comment]
New visualization of epochs on hang (outputs DOT file):

<img width="846" alt="Screen Shot 2019-10-22 at 10 06 04 AM" src="https://user-images.githubusercontent.com/3324465/67311280-1ed3d300-f4b4-11e9-9910-194a2cd42b2b.png">
