### ISSUE TITLE
Research: VRT Collection Templates slow to create

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#501]
- With Clang 9+ (Mac ports clang-devel), use -ftime-trace, ref. https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-profiler-for-Clang/
- Trace data will be generated in JSON, which can be opened with chome://tracing or (eg.) https://www.speedscope.app
- Note time taken for Collection.construct<..> upwards to 7 seconds, sendMsg upwards of 3 seconds. Probably more costly as more template code exercised.

From text_index_types.cc.json, eg:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/1430176/66620358-02bb6200-eb95-11e9-9adf-8bb5bc984a3b.png">

First instantiation especially slow, a bit faster for subsequent (different types, so much some internal reduction). Only effective exercise of 'construct' and 'sendMessage' so actual applications may be expected to perform more work than shown (many traces to choose from..).

(File too large to upload..)

**Comment by pnstickne** [comment]
"Find ways of reducing cost"
Thoughts:
- Graph shards quite fast to leaves..
- Within VT, eliminate templates when not needed
- Within VT, explicit instantiation of internal types with fixed sets
- External to VT, thin/fat headers where usages perform explicit instantiation in target domain.

**Comment by pnstickne** [comment]
Well, shoving around collection instantiation isn't going to be useful to usages.. same work, different place.

@lifflander Suggested:
- Pull template deps out entirely / employ virtual
- Pull template deps out to IndexT (significantly less sets when ColT not pulled along)

**Comment by lifflander** [comment]
We have more specific action items so I am closing this research issue.
