### ISSUE TITLE
extraneous commas

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#517]
**Describe the bug**

`INSTANTIATE_TYPED_TEST_CASE_P` macro calls have an extraneous comma at the end.  For example:
```
INSTANTIATE_TYPED_TEST_CASE_P(test_mem_serial, TestMemoryActive, MsgSerial, );
```

This macro is defined as below in the versions of gtest used by EMPIRE and vt-auto-build:
```
# define INSTANTIATE_TYPED_TEST_CASE_P(Prefix, CaseName, Types)
```

**Comment by PhilMiller** [comment]
See #512 and its fix #513

**Comment by nlslatt** [comment]
Actually, @pbmille, #513 is what caused my compile errors.

**Comment by lifflander** [comment]
Oh, this is surprising. This was causing warnings in the version of gtest we were using. Maybe we should synchronize the versions of gtest so we don't have conflicts like this?

**Comment by pnstickne** [comment]
Link - https://github.com/DARMA-tasking/vt/issues/465

**Comment by nlslatt** [comment]
@lifflander, @pnstickne We decided a long time ago to have vt-auto-build fetch a specific version of gtest due to its ever-changing interface and the need to be compatible with EMPIRE.  We aren't the only ones using EMPIRE's gtest so we might be stuck with the ancient version.  We should document what version is needed so that it can be obtained without vt-auto-build.

**Comment by PhilMiller** [comment]
Would the EMPIRE folks be opposed to that getting updated? Or is it just a matter of the effort involved?

**Comment by nlslatt** [comment]
@PhilMiller I haven't asked.  Even if it was updated, it would still be a fixed version that would eventually become stale.  Is it worth it?

@bathmatt Is there a requirement that EMPIRE's gtest stay at it's current very old version, or is there the possibility of making it more current?  vt doesn't require a newer version, but is forced to require the same version as EMPIRE.
