### ISSUE TITLE
Cleanup examples in VT

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#526]
**What Needs to be Done?**

- [ ] Clean up examples for release. Remove ones that are limited to small node counts.

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by PhilMiller** [comment]
I just went though trying to merge the 526 branch with `develop`. Most of it resolves easily, except 
>  #526: example: make ex../collection_group.cc a test instead 

I think it would be best to just integrate what goes through cleanly, and have the deck clear to tag 1.0.0. You can decide whether that example is important enough to warrant follow up on.
