### ISSUE TITLE
Null Pointer Access of type 'location::LocationManager'

### ISSUE THREAD

**Issue by uhetmaniuk** [DARMA-tasking/vt#527]
**Describe the bug**
/Users/ulrich/Dropbox/NGA/vt-examples/vt/src/vt/topos/location/location.impl.h:67:18: runtime error: member access within null pointer of type 'location::LocationManager'

**To Reproduce**
1. Build with trace_enabled

2. Compilation:
platform = macOS Catalina (but happened on macOS Sierra)
compiler = clang 3.9 
flag = "-g -fsanitize=undefined"

2. Run:
./lb_iter.exe --vt_trace

ulrich@Ulrichs-MacBook-Pro vt-examples % ./lb_iter.exe --vt_trace
/Users/ulrich/Dropbox/NGA/vt-examples/vt/src/vt/topos/location/location.impl.h:67:18: runtime error: member access within null pointer of type 'location::LocationManager'
vt: Caught SIGSEGV signal: 11 
0    18   0x10e54154c     vt::debug::stack::dumpStack(int) + 124
1    18   0x10e56977a     vt::runtime::Runtime::sigHandler(int) + 330
2    18   0x7fff6a4a6b1d  _sigtramp + 29
         3 18 0x123094268 3   ???                                 0x0000000123094268 0x0 + 4882776680
4    18   0x10e8200f7     vt::location::LocationManager::LocationManager() + 183
5    18   0x10e820032     vt::location::LocationManager::LocationManager() + 98
6    18   0x10e6070be     vt::runtime::Runtime::initializeComponents() + 140046
7    18   0x10e58b0dc     vt::runtime::Runtime::initialize(bool) + 1484
8    18   0x10e58a671     vt::runtime::Runtime::tryInitialize() + 2337
9    18   0x10e58bcb0     vt::runtime::Runtime::initialize(bool) + 4512
10   18   0x1074b0e99     vt::CollectiveAnyOps<(vt::runtime::eRuntimeInstance)0>::initialize(int&, char**&, short, bool, ompi_communicator_t**) + 13545
11   18   0x104a3f706     main + 246
12   18   0x7fff6a2a5405  start + 1
        13 18 0x2 13  ???                                 0x0000000000000002 0x0 + 2

**Comment by lifflander** [comment]
Merged, closing per #528
