### ISSUE TITLE
Printed migration count is wrong from BaseLB

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#529]
**Describe the bug**
`local_migration_count_++;` needs to be moved to the else condition on vt/src/vt/vrt/collection/balanace/baselb/baselb.cc:261

**Comment by PhilMiller** [comment]
Fix was merged in this PR:
https://github.com/DARMA-tasking/vt/pull/547

**Comment by lifflander** [comment]
Merged, closing
