### ISSUE TITLE
Trace builds of VT crash early in startup when certain callback kinds are registered (eg. reduce.cc, ~1/8 tests),

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#554]
**Describe the bug**
This is related to #342, with an expanded explanation of the problem. When compiling in trace mode, the tracing component in conjunction with the registry, generates a `*.sts` file that holds all the object types and method types for reference in the projections trace.

Here's an example sts file (I've changed the extension to txt since github does not support unknown file types): [EMPIRE_PIC-NLS-release-beta3.exe.sts.txt](https://github.com/DARMA-tasking/vt/files/3811293/EMPIRE_PIC-NLS-release-beta3.exe.sts.txt)

The log files for each node refer to the sts file when tracing/logging events that occur. To see a full trace in projections, build with `-Dvt_trace_enabled=true`, run `examples/hello_world` with "--vt_trace --vt_trace_dir=testdir`. Download projections [Projections](http://charm.cs.illinois.edu/distrib/binaries/projections/projections_6.8.0.tar.gz). Open the sts file in the directory and you can look at the "Timeline" tool.

The demangler tries to parse out the object and function/functor type using compiler-specific functions for extracting. Snippet from `src/vt/utils/demangle/get_type_name.h`:

```
#if defined(__clang__)
  StaticString p = __PRETTY_FUNCTION__;
  return StaticString(p.data() + 31, p.size() - 31 - 1);

# elif defined(__GNUC__)
  StaticString p = __PRETTY_FUNCTION__;

#   if __cplusplus < 201402
    return StaticString(p.data() + 36, p.size() - 36 - 1);
#   else
    return StaticString(p.data() + 46, p.size() - 46 - 1);
#   endif

# elif defined(_MSC_VER)
  StaticString p = __FUNCSIG__;
  return StaticString(p.data() + 38, p.size() - 38 - 7);
#endif
```

This is therefore inconsistent and compiler-specific. Not only that, but the demangler does not actually parse the type but try to pull it apart with heuristics.

**To Reproduce**
1. Build VT in trace mode (`-Dvt_trace_enabled=true`)
2. Run `make test`

**Expected behavior**
Consistent types for all compilers on all tests.

**Platform (please complete the following information):**
 - All platforms

**Comment by pnstickne** [comment]
"All compilers" is not reasonable as is is a compiler-specific detail (*maybe* improved in C++2a). Can support primary compilers and perform better extraction.

Support will be limited to approximately, as it is currently:

As supports a __PRETTY_FUNCTION__ (might be better to have cmake feature detection, to accept wherever such is provided):

   Clang .. defined (__clang__)
   GCC .. defined(__GNUC__)
   ICC .. (defined(__ICC) && (__ICC >= 600))

And, optionally:

   MSVC++ .. defined(__FUNCSIG__)

**Comment by lifflander** [comment]
That should be fine---all compilers is probably too aggressive as long as our current supported targets work. I would expand that to include nvcc, which probably uses a reasonable frontend.
