### ISSUE TITLE
Color is not output by default on termination anymore (after merging #544)

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#556]
**Describe the bug**
@pnstickne After merging issue #539, PR #544, the color stopped outputting by default in a normal terminal.

**To Reproduce**
1. Run any test/example.

**Comment by pnstickne** [comment]
There ya go. Minimal lies.

<img width="747" alt="Screen Shot 2019-11-10 at 3 18 03 PM" src="https://user-images.githubusercontent.com/1430176/68552626-c6fefc80-03cd-11ea-88fc-95a34ee862ff.png">
