### ISSUE TITLE
--vt_lb_stats_dir not being parsed correctly in EMPIRE on Mutrino

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#567]
**Describe the bug**
Try to specify a directory using `--vt_lb_stats_dir`

**Comment by pnstickne** [comment]
Another issue (related?) seems to be that unknown `--vt_` (or args in general) are causing "various program crashes"; if a build doesn't have a particular option available it could thus have similar results. :|

**Comment by pnstickne** [comment]
Also, `--help` (and maybe a `--vt_help`) should probably terminate the program..

@lifflander In addition to resolving above, what about:

     mpirun vt/program --vt_arg_1 --vt_arg_2 -- --arg-to-prog1 --arg-to-prog2
