### ISSUE TITLE
Missing SendRecv comm lines between objs in EMPIRE stats

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#574]
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by nlslatt** [comment]
@lifflander Is this related to #610?

**Comment by lifflander** [comment]
No, this is different. It's about the instrumentation that is collected for LB stats. It doesn't go through the trace interface.

I tried to re-produce this; I think this bug might not exist and I was reading the stats wrong. I need to confirm this because if the bug exists I need to get this in the release

**Comment by PhilMiller** [comment]
Is this bug still salient? It's almost 8 months old at this point.

**Comment by lifflander** [comment]
No, I'm going to close this. I don't think this bug ever existed...
