### ISSUE TITLE
VT link error due to missing dladdr (Ubuntu Disco / Clang 9).

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#603]
When linking *to* VT (eg. from example apps):

    /usr/bin/ld: ../src/libvt-debug.a(runtime.cc.o): undefined reference to symbol 'dladdr@@GLIBC_2.2.5'
    /usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line

This does not affect local OS X machine (maybe libraries are implicitly added by default?)

Regression between origin/develop (a74cd43184cfcedde354b91275017346e8937504) and all 1.0.0-beta branches (eg. origin/1.0.0-beta.5-proposed-update).

Used in:

    s1044664ca:vt pnstick$ ag dlfcn
    src/vt/configs/error/stack_out.h
    56:#include <dlfcn.h>
    s1044664ca:vt pnstick$ ag dladdr
    src/vt/configs/error/stack_out.h
    82:    if (dladdr(callstack[i], &info) && info.dli_sname) {

**Comment by pnstickne** [comment]
Ready to go, assuming such does not affect a down-steam compile.

**Comment by lifflander** [comment]
Closing, merged. Also applying to develop
