### ISSUE TITLE
Fix Clang 3.9 initialization bug with event containers

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#611]
Clang 3.9 does not work with tracing, full stop.
There may be an issue with the unique_ptr not being correctly constant-initialized.

**Comment by pnstickne** [comment]
@lifflander So, being Clang 3.9 is woefully outdated, it is not available via either Macports (does list 3.4, which won't install on Mjovae) or Ubuntu's apt (min is Clang 6), nor is there a supported build on the LLVM package repo for such.

Anyway, I suspect the issue may be related to DR1301 and how one might define value-initialization.

The previous changes were explicitly designed to induce constant-intialization of a unique_ptr per C++14 specs (if it is dynamically initialized the behavior is UB; and the compiler is doing C++14 wrong).

In trace_container.cc the types should have constant initialization per the specification (to avoid all dynamic initialization ordering issues entirely).

```
// These MUST have static-lifetime and be initialized during constant
// initialization as they are modified during dynamic initialization as
// that is when auto-handler events are registered.
// Using a constexpr constructor / initializer list is also relevant.
// - https://en.cppreference.com/w/cpp/language/constant_initialization
static std::unique_ptr<TraceContainerEventClassType> event_type_container_{};
static std::unique_ptr<TraceContainerEventType> event_container_{};
```

It may be possible that the `{}` of value-initialization *may* be triggering different behavior in Clang 3.9 (possibly see DR1301, closest I can find); the following would thus avoid the value-initialization case entirely while still be constexpr:

```
static std::unique_ptr<TraceContainerEventClassType> event_type_container_;
static std::unique_ptr<TraceContainerEventType> event_container_;
```

or

```
static std::unique_ptr<TraceContainerEventClassType> event_type_container_{nullptr};
static std::unique_ptr<TraceContainerEventType> event_container_{nullptr};
```

**Comment by pnstickne** [comment]
Alternatively, if such do not address the issue and static-inside-a-function does .. then that's obviously a simple course of action. Hopefully with some comments calling out Clang 3.9 behavior.

Alternatively, consider Clang 5 (still 4 major versions back!) as min target so that I can play along >_>

**Comment by pnstickne** [comment]
@lifflander Built with Clang 5.0 off of *origin/develop* (as the beta-5 does not include the trace name update fixes to prevent crashes) - all expected STS entries are present.

**Comment by pnstickne** [comment]
More specifically, [DR1301](https://wg21.cmeerw.net/cwg/issue1301) affects the case of "if the initializer list has no elements".. the two provided alternatives above should this be free from any potentially ambiguous application.

**Comment by PhilMiller** [comment]
Is there some imperative to maintain Clang 3.9 support, from EMPIRE or from DARMA management? Are there systems where that's the relevant version anymore? I'd be much more inclined to drop that than to contort the code to accommodate a bug in such an old version.
