### ISSUE TITLE
rdma: Possible memory leaks

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#625]
**Describe the bug**

I was auditing all of the sites in `src/` that do a bare `new` (`git grep 'new '`), and most everything ended up having an obviously paired delete or transfer of ownership. The one cluster of exceptions that I came across was in `src/vt/rdma/rdma.cc`, with three instances of `new Action` that seem to be leaked

**Platform (please complete the following information):**
 - vt commit f14afcf57

**Comment by lifflander** [comment]
Unless address sanitizer is complaining I think we are fine.
