### ISSUE TITLE
Traces are hard to understand with system level handlers

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#631]
**Describe the bug**

For every message application code sends, the resulting traces of the corresponding handler will show several events, logically nested but actually broken up by the unstacking code in the trace writer. This makes application performance analysis difficult, since none of those handlers are things the user explicitly called for, and computed message receive counts are a variable multiple of send counts.

**To Reproduce**

Run an application sending messages to handlers that are methods of process, objgroup, or collections, and look at the pile of beginProcess/endProcessing events wrapped around each application-level handler.

**Expected behavior**

Unless the user asks otherwise, all of those system-level wrapper handlers should be treated as overhead, or fully attributed to the innermost handler.

**Screenshots**

**Comment by PhilMiller** [comment]
@lifflander I'm trying to walk through the tracing registry code to figure out how to come up with the trace ID numbers for the handlers I care about outside the normal call path. I can't follow it from one end to the other.

What I want to do is add an `unordered_set<EventID> system_handlers` that will get special treatment, and a call to add things to that by name.

With their work on #241 maybe @pnstickne or @uhetmaniuk can help me out.

**Comment by lifflander** [comment]
I have a reasonable idea of how to accomplish this. We may want to chat about it.

**Comment by lifflander** [comment]
The second part of this is connecting the trace "event" seq number that Projections uses to track dependencies with the innermost block, which will become the outer one with system trace off. Also, even when system tracing is on, we should push that event to the inner events so all of them track the appropriate dependency which will greatly improve usability.

**Comment by pnstickne** [comment]
Yes, this is a little .. fun with the trace writing. It also represents a de-optimization point.

Ideally, I believe it would be good to either 1) emit only a single END event (with start + stop times) or 2) emit a SINGLE start event with a sentinel stop (duration only); and have the processing application perform any visual re-ordering as the user desires.

This can then move the event 'stack' outward easily and support both inline-stack and async cases:

     int eventId = beginEvent(....);
     // ..
     // on stack unwind (or even in an async lambda OFF of the stack)
     endEvent(eventId);

The coupling/overlap of events moves to the visual processing application instead of internal association or sharding of.

**Comment by pnstickne** [comment]
(Also consider idle-event interleaving.)

**Comment by pnstickne** [comment]
For association of well-known handlers, some thoughts:
- Associate in-post by rendering client (requires external sync)
- Associate in-post by name mapping defined in source
- Associate by name during handler registration (all the registrations should now flow through a consistent 'RunnableT' triplet where the trace names are generated).
- Add a 'setTraceName'-like construct for well-known names and/or IDs
- Expand auto-handler templates to accept a well-known name/ID.
