### ISSUE TITLE
Memory error in transpose example

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#634]
**Describe the bug**
Running transpose with 4 MPI ranks shows a memory bug.
`mpirun -np 4 valgrind —log-file=foo.%p transpose`

**Comment by lifflander** [comment]
@uhetmaniuk Can you try to solve this bug? It only shows up occasionally on some platforms. Maybe you can read the code for the `transpose` example and see if there is an obvious problem?

**Comment by uhetmaniuk** [comment]
@lifflander Is there a specific compiler (and/or OS) that triggers the bug?
