### ISSUE TITLE
Unify public API for send + broadcast

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#656]
Since #633 is turned more into a case of ensuring semantics and ownership (not types), this task is a FOLLOW ON to #633 (in particular, it utilizes the funneled code) to:

Explore / implement a send/broadcast client-facing API to:
- Not require the use of a Msg* (and thus makeSharedMessage)

This avoids some odd constructs like `send(makeMessage<T>(..).get())` while avoiding code like this `auto* ptr = makeSharedMessage<T>(..); if(maybe_send) { send(ptr); }` which can introduce a memory leak as the shared pointer is never automatically managed.

This probably means the ability to accept a MsgPtr directly (as & and &&) to allow common use-cases a user might encounter.

Care should be take to avoid divergence and unnecessary method override bloat..

**Comment by pnstickne** [comment]
One of the issue with the current API is an EXCESSIVE number of overloads. While these have been paired down with an optional tag parameter, there are still 3x duplicate overall.

The API design I'd _like_ to move towards is:

    theMsg()->send<T>(msg, handler, tag = opt)

To make this type-safe, a HandlerWrapper<T> type can be used. The overall usage might then look like:

    theMsg()->send<MyMsg>(
        makeMessage<MyMsg>(args, ...),
        makeHandler<MyMsg, HandlerFn>()
    );

There is a slightly duplication in the `makeHandler<MyMsg>`, which I'm not sure how to eliminate without adding something like: MsgPtr->makeHandler<..>.

The msg accepted should be a MsgPtr& (when message is a local) and a MsgPtr&& (for ref / inline makeMessage), so _all_ handlers can be accounted for in only 2 overload of the `send` method.

**Comment by pnstickne** [comment]
It's also possible to add forwarding type, especially with a more fluent design. (Basically replacing `makeMessage` with forwarding ctor.)

     UserMsg<..>{..}.sendWithHandler<..>();

**Comment by pnstickne** [comment]
Given a few more changes, it would might be possible to safely accept `send` for any xref to an object.

     send<MyMsg>(MyMsg{..}, ..)  // accepted as MyMsg&&

When then very clearly exposes when a MyMsg is created.

**Comment by lifflander** [comment]
I have several thoughts about this:

1. I think we should remove the `tag` from the sending interface. 

All the AM does is just add the tag to the envelope of the message. In the few cases where tags are used, the user can just do an `envelopeSetTag(msg->env, tag)` or the user can calls a nicer overload we provide `messageSetTag(msg, tag)` before sending. Sending a message multiple times with different tags (with automatic copy) does not seem like a particularly useful operation to be.

The tag-specific registration of handlers should be removed. Currently, the interface allows you to register a handler that just picks up a certain tags. No clients have ever used that interface; and it adds overhead in the dispatch code. Also there is a buffering mechanism for when a handler is only registered on a node for a certain tag and a message arrives with another tag. It buffers and waits for registration of a sufficient handler. We can reduce implementation complexity a lot if we remove this I think.

2. Some considerations if we don't pass the handler directly as a template:

    - Right now, I can grep/read through code for `sendMsg` and immediately see the handler it's going to fire. It's always in the same spot and easy to find on a `sendMsg` line. I don't really want client code hiding their handler creation far from the callsite.

    - I'm not against "fluent API" design, but unless we are going to expose many other operations to messages beyond just `send`, it doesn't seem to make sense from a consistency standpoint. There is a side of me that thinks this design could be useful for making a cleaner reduce interface (for instance) when a proxy is not involved. 
`msg.reduce<PlusOp>().toHandler<&finished>()`. 

@PhilMiller I would like your feedback on this issue.

**Comment by lifflander** [comment]
The other side of the interface we should consider is the receive-side. With `MsgSharedPtr<MsgT>` nearly required on the send-side, does it make sense that it should arrive that way in the handler also?

```C++
void myHandler(MyMsg* msg) {
  // how do I know if I'm allowed to hold on to msg and re-use it?
}

void myHandler(MsgSharedPtr<MyMsg> msg) {
  // I can easily throw MsgSharedPtr in a container to re-use it or do something with it
}
```

I don't think we can get rid of raw pointer message handlers because they are so prolific. I think we should need a second interface for `MsgSharedPtr<MsgT>`

**Comment by PhilMiller** [comment]
If tag arguments have turned out not to be useful, I'd agree that we should strip them out, and simplify the overload sets accordingly.

I concur that handlers should preferentially be present as literal template arguments, and not as value arguments to the send/bcast functions. If there's no indirection or abstraction of handlers going on, code is much more readable if they're hard baked in. Looking ahead, to parameterization, the handler as template argument also supports proper detection of the argument types and their packing.

I would be against having `send` be any sort of member of message - it makes much more sense as an operation on some sort of proxy for a recipient. If anything, perhaps at the user API level, we would even add a `NodeProxy` class, rather than having callers directly address `theMsg()` in that case, but not in the objgroup or collection case.

**Comment by lifflander** [comment]
In favor of a `NodeProxy` class as an alternative API that would align with objgroups. We could even re-use the objgroup proxy code with a special "global" objgroup. The objgroup proxy building already has the `Args&&...` builder for the message in its interface. So that solves a couple problems.

**Comment by lifflander** [comment]
Based on the discussion in the meeting, we are going to try a implicit conversion to `MsgToSend<T>` (or something like that) that takes ownership of the message being sent. Or the sendMsg may be called inline with `makeMessage<T>(...)`.

**Comment by lifflander** [comment]
The useful parts of this have been implemented.
