### ISSUE TITLE
Cleanup Msg Shared Refs + Enforce Message Contracts

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#665]
Split-up work of #633 - follows on #657 (Active Message cleanup) and precedes #656 (improved Message API).

This work represents some breaking contract changes. Violating code will have to be fixed, although it is hopeful that assertions can be used to quickly identify issues.

The "correct" way to use VT should also be added to the Wiki/documentation.

Some changes:
- Cleanup handling of promoteMsgOwner and message ownership model. The change are expected to REJECT all messages not created as a 'shared message' in some manner. That is, `new Msg{..}` is an invalid construct for a VT active message.
- Prohibit re-transmission of the same message object. This includes one received in a handler callback. The reason for this is that it eliminates some silent side-effect mutations of state in the envelope which might not be expected.. as the envelope is currently part of each AM.

**Comment by PhilMiller** [comment]
#748 got merged. Should this be closed?

**Comment by lifflander** [comment]
> #748 got merged. Should this be closed?

Yes
