### ISSUE TITLE
Enhance PendingSend for multiple sends and add support for objgroup

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#688]
**What Needs to be Done?**

We need support for multiple sends. It should push/pop also. We can cleanup much to the manual `PendingSend` creation code (like in `sendMsgUntypedHandler` in the VRT collection manager) if that becomes the case.

**Comment by PhilMiller** [comment]
There's several requests kinda bundled up here. I generally see how they fit together, but if you have more elaborated thoughts on your vision, it would be useful to have them written down.

**Comment by PhilMiller** [comment]
For the multiple-message use case, what do you think of the approach of adding a method along these lines:

```c++
template <typename MsgT>
void PendingSend::addMessage(MsgSharedPtr<MsgT> in_msg, SendActionType const& in_action)
{
  send_action_ = [=, old_msg = msg_, old_size_ = msg_size_, old_action = send_action_]
            (MsgVirtualPtr<BaseMsgType> &msg) {
    old_action(old_msg);
    in_action(in_msg);
  };
}
```

With a suitable overload for a simple sized message, assertions about the epochs matching , etc.

**Comment by nmm0** [comment]
@lifflander @PhilMiller I can split objgroup support into a separate issue, and would be up for working on it now that I finally have some time. I need it for some of my contact code

**Comment by PhilMiller** [comment]
The use case for multiple sends in EMPIRE has become moot.

**Comment by lifflander** [comment]
> The use case for multiple sends in EMPIRE has become moot.
> […](#)

In that case, let's leave this issue open until we are sure, but let development continue on https://github.com/DARMA-tasking/vt/issues/702 for the required use cases, headed up by @nmm0

**Comment by lifflander** [comment]
This is done.
