### ISSUE TITLE
Tracing: general fixes and improvements

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#717]
- Either disable the ability to enable/disable tracing via the runtime flag or fix it. If tracing is stopped while a processing event is opened and not resumed before the processing event is finished, the open event stack will become corrupted and lead to application crashes.

- Remove the auto-close idle logic. This is not necessary (and can cover bugs) with the proper use of using `runSchedulerWhile` for nested schedulers.

- Remove usage of `getTime()` from default arguments, and remove `getTime` from methods entirely in cases it is not relevant.

- Visit idle schedule event setup: "These [vector.resize calls] should be initializers to the intended size, probably where they're declared, since that's a constexpr size."

**Comment by lifflander** [comment]
Closing as it doesn't seem relevant right now.
