### ISSUE TITLE
Adjust location manager migration nomenclature 

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#746]
**What Needs to be Done?**

- [ ] Rename these various functions with Immigrated (e.g. `entityImmigratedFrom`) and Emigrated (`entityEmigratedTo`), so it's clearer which end each one gets called on?

**Is your feature request related to a problem? Please describe.**

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by lifflander** [comment]
@bradybray We want to improve the names in the EntityLocationCoord to use proper terminology for elements immigrated/emigrating: https://github.com/DARMA-tasking/vt/blob/c959dbc5f3c8f34c3df39a2f76bce5fe094df407/src/vt/topos/location/location.h#L155-L185

**Comment by bradybray** [comment]
@lifflander I assume if I change these then it must propagate out to the respective callers?
