### ISSUE TITLE
vtConfig.cmake installed in cmake/ directory

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#780]
On unix/linux systems vtConfig.cmake is typically installed in something like <prefix>/lib/cmake/vt though <prefix>/share/cmake/vt might make more sense. Either will work correctly with CMAKE_PREFIX_PATH and for newer versions of CMake vt_ROOT

https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

**Comment by nmm0** [comment]
Edited because CMAKE_PREFIX_PATH does still correctly find it, but it's not a typical location for the file

**Comment by lifflander** [comment]
Where does it currently install it?

**Comment by lifflander** [comment]
Works as intended. We will reopen when someone has a problem finding it again.
