### ISSUE TITLE
Compute new statistics for LB: average obj load, marginal obj load

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#810]
**What Needs to be Done?**

In the beginning of load balancing, when process-level and global statistics are computed, my work is leading me to think that we might benefit from a couple additional indicator statistics:

* Average object load on each process and globally
* Load of the 'marginal' object on overloaded processors - i.e. the heaviest object that *must* be moved in order to achieve balance

**Is your feature request related to a problem? Please describe.**

The reason I want these is that in any refinement-style strategy, we need to be able to distinguish whether balance is directly achievable, or whether there is no 'hole' large enough to move the worst-case object from an overloaded process. That case necessitates picking some additional process that may not be overloaded, but nevertheless needs to unload some objects to make room for another. If that is necessary, then we want to pick a process that has small objects, so that they can be easily offloaded without having to apply this reasoning recursively.

**Describe potential solution outcome**

**Describe alternatives you've considered**

**Additional context**

**Comment by lifflander** [comment]
Marginal load is implemented, closing this issue
