### ISSUE TITLE
Switch from gtest_add_tests to gtest_discover_tests

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#823]
https://cmake.org/cmake/help/latest/module/GoogleTest.html

gtest_add_test is the traditional method to register tests in CMake. However it is prone to source code regex scanning. gest_discover_tests is the newer method and properly works with a wider range of tests as it queries the target executables themselves to determine what tests are available.

Per a pervious attempt, this will require some test updates to function correctly.

**Comment by lifflander** [comment]
Pl. refer to https://github.com/DARMA-tasking/vt/issues/226

**Comment by lifflander** [comment]
This doesn't work because it explodes all the tests leading to long test times.
