### ISSUE TITLE
Trace inside/outside VT with event with runSchedulerWhile used everywhere

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#854]
**Describe the bug**
We currently have a inconsistent trace with idle time. See attached.
<img width="1767" alt="Screen Shot 2020-06-10 at 2 02 25 PM" src="https://user-images.githubusercontent.com/3324465/84318447-4c44be00-ab23-11ea-9f07-852f244e1568.png">

**Comment by pnstickne** [comment]
@lifflander 
"As designed".

Thoughts:
- Add a new top-level scheduler construct to be used "out side of" VT. `runSchedulerWhile` should only be used inside VT (or a handler of such).
- E.g. `runSchedulerUntilTerm`/`runSchedulerUntilTermOr`. When in these forms will close/open a single user event signaling "unknown operations external to VT".

**Comment by lifflander** [comment]
Adding a top-level scheduler call sounds reasonable to me. You might want to look at the new scheduler functions that @PhilMiller added: `runInEpochCollective`, `runInEpochRooted`, which will run until a more specific termination event

**Comment by pnstickne** [comment]
@lifflander Where are those functions defined? :|

**Comment by PhilMiller** [comment]
This was addressed in #888
