### ISSUE TITLE
Make ZoltanLB work when IDs are not 64-bits

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#861]
**What Needs to be Done?**

Currently, ZoltanLB static asserts that the Zoltan IDs for identifying graph nodes are 64-bit variants, meaning that Zoltan was built with `-D Zoltan_ENABLE_ULLONG_IDS:Bool=ON` enabled in cmake. However, for the default Trilinos installs (such as the ones that EMPIRE uses), Zoltan is built, but this option is not enabled. Thus, ZoltanLB can't be run in EMPIRE without rebuilding Trilinos or getting them to change the default configuration.

VT needs 64-bits to identify an object (due to how it stamps the node into the identifier); thus, the smaller IDs will not work unless we compress the bits. 

Thus, I recommend that we use the Zoltan mode where two IDs can be used as a single ID; i.e., 64-bits are simulated by combining two IDs. Zoltan has built-in support for this mode. We can statically switch between these modes based on the ID size.

**Comment by PhilMiller** [comment]
Another possibility would be to do a configure time check for this, and not
enable ZoltanLB if the settings aren't appropriate.

I'm not sure if we're committed to making ZoltanLB available though, or
some other broader context.

**Comment by nlslatt** [comment]
I agree that our decision should take into account expectations for ZoltanLB availability.  Is it just so we can say that, yes, we've done that experiment and, yes, it was worth investing in us?  Or, at the other extreme, does ZoltanLB need to be available by default for nightly testing and everything else?  If the expectation is that we can build with Zoltan but rarely will, then I'm not sure it's worth jumping through hoops to be compatible with Zoltan's default configuration.

**Comment by lifflander** [comment]
I think it depends on how well ZoltanLB performs. It is useful from a programatic perspective to have Zoltan capability, which is fulfilled with the implementation already. If we want to be compatible with Trilinos out-of-the-box this is going to be useful to have so we don't have to tell folks to re-compile with that flag. I think if it's not too difficult we should just do it to make it easier for apps to evaluate the benefits of using Zoltan as a backend LB.

**Comment by lifflander** [comment]
I don't think it's too much to ask for the configure flag to be there. If it becomes a burden we can readdress this.
