### ISSUE TITLE
Fix user event trace types with wrong typedef UserEventIDType vs TraceEventIDType

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#877]
**What Needs to be Done?**

A lot of callsites (see `src/vt/trace/trace_user.{h,cc}`) don't use the right type of user event IDs, which have their own typedef. Switch these over, if only to clarify the user/system interface of what is expected at those callsites.

**Comment by pnstickne** [comment]
The issue that "get" me is the name are so similar.

Also, is there a way to strengthen type-checks over a typedef? Simple wrapper structs?

**Comment by lifflander** [comment]
Yes, take a look at `vt::Strong`. We should push this up beyond reducers.

https://github.com/DARMA-tasking/vt/blob/develop/src/vt/collective/reduce/scoping/strong.h
https://github.com/DARMA-tasking/vt/blob/develop/src/vt/collective/reduce/scoping/strong_types.h

**Comment by pnstickne** [comment]
> Yes, take a look at `vt::Strong`. We should push this up beyond reducers.
> 
> https://github.com/DARMA-tasking/vt/blob/develop/src/vt/collective/reduce/scoping/strong.h
> https://github.com/DARMA-tasking/vt/blob/develop/src/vt/collective/reduce/scoping/strong_types.h

C++ templates for this feel a teeny bit dirty - I'm definitely not a template fan 🌵 
What about code-gen templates?

**Comment by pnstickne** [comment]
https://www.fluentcpp.com/2017/05/05/news-strong-types-are-free/

**Comment by lifflander** [comment]
Seems to not be a real problem right now. We don't want to convert everything to use Strong types because of the compile time increase it might cause.
