### ISSUE TITLE
Make debug_print macro in VT include vt_ in the name

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#881]
**What Needs to be Done?**

The `debug_print(..)` macro bleeds into application code because it's a macro. Let's rename it to `vt_debug_print(..)` so that the name at least includes VT.

**Comment by lifflander** [comment]
In general we should look at: `src/vt/configs/debug/debug_print.h`, etc. to see if we need to rename some macros. We also might be able to undef some of them that are used to build up an exposed macro.

**Comment by PhilMiller** [comment]
That undefing is not going to work as you think. Later macro definitions don't capture the set of definitions existing at the point of their own definition. They just do text expansion at the point of appearance. If you undef the bits used in implementation, they'll just end up as undefined literals in the expansion.

So, they're instead going to need long, ugly, obscure prefixes on their names, to avoid collisions.

We can also try to push as much as possible out of macros, or as macros only used inside template functions that will capture the expansion as their definition.
