### ISSUE TITLE
vtAssert fails in BaseLB about migrateObjectTo

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#885]
**Describe the bug**
In `22bf5db3359b8a9f5f6c14ad9ba9d0ac598db128`, an assertion was added to develop that if `migrateObjectTo` is called a current migration epoch is open. However, this assertion fails inside BaseLB! This is the case where the migration needs to transferred to another node:

```C++
void BaseLB::transferMigrations(TransferMsg<TransferVecType>* msg) {
  auto const& migrate_list = msg->getTransfer();
  for (auto&& elm : migrate_list) {
    auto obj_id  = std::get<0>(elm);
    auto to_node = std::get<1>(elm);
    vtAssert(theProcStats()->hasObjectToMigrate(obj_id), "Must have object");
    migrateObjectTo(obj_id, to_node);
  }
}
```

This assertion is causing all my runs with LB to fail on develop.

**Comment by PhilMiller** [comment]
#866 effective addresses this, by removing the migration epoch from the LB strategies entirely. It should be entirely ready to merge if you just want to take it.
