### ISSUE TITLE
MPI tracing for external library (use case for #900)

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/vt#903]
This is a use case for #900 

In NimbleSM we would like to do a detailed performance comparison between a darma-based contact backend and an MPI-based backend from an external library. It would be useful if we don't have to initialize VT when running the MPI-backend but it's fine to still link against VT.

**Comment by lifflander** [comment]
@pnstickne

**Comment by pnstickne** [comment]
@nmm0 I'm missing context. It should still be possible to link against VT.

Is the ask to allow collecting PMPI from this other executable? Or is there some issue with linking when the PMPI compile time support is enabled?

**Comment by nmm0** [comment]
> @nmm0 I'm missing context. It should still be possible to link against VT.
> 
> Is the ask to allow collecting PMPI from this other executable? Or is there some issue with linking when the PMPI compile time support is enabled?

@pnstickne Basically I'm curious if it would be possible to use the tracing/profiling capabilities directly in an MPI program that is not using VT calls. It's fine if it links against VT. We want to do vt backend vs non vt backend performance comparisons

**Comment by lifflander** [comment]
@pnstickne I think this is an interesting idea to support this mode. Fundamentally, we need the `vt::theTrace()` to support trace-only mode. The trace component doesn't send messages except for some special cases in `src/vt/trace/trace_user_event.cc`. So we could fire up a stripped down version of VT that can just output MPI traces from PMPI wrappers. What do you think?

**Comment by PhilMiller** [comment]
If minimal code modification is acceptable, then why not just add calls to vt's initialization and shutdown routines in the application's main? It doesn't add any runtime overhead of its own, beyond what the tracing would do anyway,
