### ISSUE TITLE
Branch to resolve 708 not fully integrated on stable branch

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/vt#929]
**Describe the bug**

Compare #826 to what made it onto the release branch.

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

**Comment by lifflander** [comment]
Merged, closing
