### ISSUE TITLE
NVCC incorrectly treats messages deriving from optionally serializable base-types as requiring serialization

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#949]
Stub story for NVCC-related issues with serialization/non-serialization detection.

Issues / suspected:

- decltype in SFINAE (used for is_same with resolved template..) throws an error instead of failing..
- A and B in the surrounding template does not appear to short-circuit. This might be an artifact of previous issue. It also does not result in a final "correct" detection as messages can still be detected as needing to be serialized in certain cases.
- Added 'isByteSerializable' trait, even though such is only needed due to above issue(s).
- Comments relating to above work-arounds in code tagged with #949 (this).

Ref. #908

**Comment by lifflander** [comment]
no longer relevant.
