### ISSUE TITLE
Add documentation about epoch tracking during reductions

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#954]
**What Needs to be Done?**

The reason why epochs are tracked correctly during reductions is a little tricky and not obvious from reading the code. Add some details about how this works to the documentation. Maybe include some info about other components also.

**Comment by PhilMiller** [comment]
Would you like me to pick this up? I understand the reasoning well enough to write it up.

**Comment by lifflander** [comment]
Yes, good idea.. I'll assign it to you.
