### ISSUE TITLE
Add some more tests for various load models

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#959]
**What Needs to be Done?**

The `PerCollection` model is tested (along with couple other points in the model codepath), but mostly the load models lack any testing. Write unit tests for them.

**Comment by lifflander** [comment]
@JacobDomagala Can you work on this issue next? I want to get some more testing in place for the load models. If you have questions about how they are supposed to work, query me or @PhilMiller.

**Comment by JacobDomagala** [comment]
Note to self https://github.com/DARMA-tasking/vt/issues/582 could be useful.

**Comment by JacobDomagala** [comment]
@lifflander  @PhilMiller  Let me know if you have any particular tests in mind for any of the load models. In the meantime i will study the code and docs to get more familiar with the topic and maybe will try to come with some useful tests aswell.

**Comment by JacobDomagala** [comment]
@PhilMiller  I've got a question about `Norm` load model. Depending on whether `power_` passed in `Norm`'s constructor is finite or not,  getWork function will execute one of the for loops:

```
// power_ is finite
for (int i = 0; i < getNumSubphases(); ++i) {
  auto t = ComposedModel::getWork(object, offset);
  sum += std::pow(t, power_);
}
```

```
// power_ is infinite
for (int i = 0; i < getNumSubphases(); ++i) {
  auto t = ComposedModel::getWork(object, offset);
  max = std::max(max, t);
}
```

Does this mean that consecutive calls to base model's getWork (which is called by ComposedModel::getWork) with the same params will return different values of work for each call? Or should we iterate over all subphases in a given phase (I assumed that it's possible that phase can consist of multiple subphases, but i wasn't able to find any information about it)

**Comment by PhilMiller** [comment]
Yeah, I screwed that up, there should be `offset.subphase = i;` in the loop. It's supposed to be an iteration over all the subphases in a given phase, as you surmised.

Your inquiry also leads me to think a little more about how the `Norm` and `Multiphase` models ought to interact. Right now, if someone has a Multiphase model stacked atop a `Norm` model, it will effectively produce a 1-norm of the successive phases, when the 'natural' thing to do may be to actually treat multiple future phases worth of subphases as all part of a single future phase, and apply the norm across them.
