### ISSUE TITLE
Don't use MPI to launch non-parallel tests

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#990]
Some tests are failing periodically (eg. those that access a shared file) as MPI is spawning multiple processes even though such tests are not MPI-aware.

An easy to reproduce failure is the LB reader tests which use a fixed filename. Different processes will stomp on each other. Run manually with MPI and '-n 20' is reproduce. The more N, the higher likelihood of conflicting.

These tests are not expected (cannot) use MPI nor do they do any VT initialization.

Ideas:
- If a test file has '.nompi' in the name, launch it directly without MPI (and only use one process..)
- Still init MPI, and bypass all nodes except Rank 0. This would still cause "extra" tests to run for 2/4/n procs.

**Comment by PhilMiller** [comment]
Fixed by #998
